### ISSUE TITLE
Adding `cmake` as an input causes the stdenv to try to build the entire expression with cmake instead of cargo

### ISSUE THREAD

**Issue by rushmorem** [ipetkov/crane#104]
Having `cmake` in Nix dependencies breaks the build with the following error message:-

```
CMake Error: The source directory "/build/dummy-src" does not appear to contain CMakeLists.txt.
```

I tried `depsBuildBuild`, `nativeBuildInputs`, `buildInputs` and even `depsTargetTarget`. Putting `cmake` in any of those for a project that doesn't contain `CMakeLists.txt` causes it to abort with that message. I'm not sure if this is the expected behavior or not but it's surprising.

I was able to get around this by using the environment variable `CMAKE = "${pkgs.cmake}/bin/cmake"`. ~~However, doing this seems to override `gcc` from `stdenv` and uses the latest `gcc` instead. I suspect that's why `overrideScope'` didn't work for me in this discussion https://github.com/ipetkov/crane/discussions/99. I even ran into this as well when I tried the PR for ergonomic `stdenv` here https://github.com/ipetkov/crane/discussions/99#discussioncomment-3655905. I had to initialize a new project with no Nix dependencies to verify that the new PR was in fact working.~~

Edit: I'm not so sure about this anymore. Commenting out the environment variable still brings in the newer `gcc`. This is strange because it was working fine with `naersk` before switching to `crane`.

**Comment by dpc** [comment]
Interesting. I tried in my project, by just:


```
> git diff
diff --git a/flake.nix b/flake.nix
index b2b73c736..0af864fdc 100644
--- a/flake.nix
+++ b/flake.nix
@@ -141,6 +141,7 @@
           src = filterWorkspaceFiles ./.;
 
           buildInputs = with pkgs; [
+            cmake
             clang
             gcc
             openssl

```

and indeed I've got:


```
> nix build .#workspaceBuild
warning: Git tree '/home/dpc/lab/fedimint' is dirty
error: builder for '/nix/store/4fvp4aqkjx882blhbrllvmljqzv3rz1f-workspace-deps-deps-0.0.1.drv' failed with exit code 1;
       last 10 log lines:
       > unpacking source archive /nix/store/31plhj7fld43www31lhf7dc6bx1xn3my-dummy-src
       > source root is dummy-src
       > patching sources
       > Executing configureCargoCommonVars
       > configuring
       > will append /build/dummy-src/.cargo-home/config.toml with contents of /nix/store/a4p08jfqw8p1czhxjip0qldhyn14y45b-vendor-cargo-deps/config.toml
       > fixing cmake files...
       > cmake flags: -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_BUILD_RPATH=ON -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LOCALEDIR=/nix/store/qnjbz35ra1rzwph2lizl49n5gy3rgvhb-workspace-deps-deps-0.0.1/share/locale -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/qnjbz35ra1rzwph2lizl49n5gy3rgvhb-workspace-deps-deps-0.0.1/libexec -DCMAKE_INSTALL_LIBDIR=/nix/store/qnjbz35ra1rzwph2lizl49n5gy3rgvhb-workspace-deps-deps-0.0.1/lib -DCMAKE_INSTALL_DOCDIR=/nix/store/qnjbz35ra1rzwph2lizl49n5gy3rgvhb-workspace-deps-deps-0.0.1/share/doc/workspace-deps-deps -DCMAKE_INSTALL_INFODIR=/nix/store/qnjbz35ra1rzwph2lizl49n5gy3rgvhb-workspace-deps-deps-0.0.1/share/info -DCMAKE_INSTALL_MANDIR=/nix/store/qnjbz35ra1rzwph2lizl49n5gy3rgvhb-workspace-deps-deps-0.0.1/share/man -DCMAKE_INSTALL_OLDINCLUDEDIR=/nix/store/qnjbz35ra1rzwph2lizl49n5gy3rgvhb-workspace-deps-deps-0.0.1/include -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/qnjbz35ra1rzwph2lizl49n5gy3rgvhb-workspace-deps-deps-0.0.1/include -DCMAKE_INSTALL_SBINDIR=/nix/store/qnjbz35ra1rzwph2lizl49n5gy3rgvhb-workspace-deps-deps-0.0.1/sbin -DCMAKE_INSTALL_BINDIR=/nix/store/qnjbz35ra1rzwph2lizl49n5gy3rgvhb-workspace-deps-deps-0.0.1/bin -DCMAKE_INSTALL_NAME_DIR=/nix/store/qnjbz35ra1rzwph2lizl49n5gy3rgvhb-workspace-deps-deps-0.0.1/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_OSX_SYSROOT= -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_STRIP=/nix/store/ag2bpk0lzjvj409znklrz5krkpc5imzs-gcc-wrapper-11.3.0/bin/strip -DCMAKE_RANLIB=/nix/store/rq6bh3qfrqnyqwik0w3q6w180zg3w2pa-binutils-2.38/bin/ranlib -DCMAKE_AR=/nix/store/rq6bh3qfrqnyqwik0w3q6w180zg3w2pa-binutils-2.38/bin/ar -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=/nix/store/qnjbz35ra1rzwph2lizl49n5gy3rgvhb-workspace-deps-deps-0.0.1
       > CMake Error: The source directory "/build/dummy-src" does not appear to contain CMakeLists.txt.
       > Specify --help for usage, or press the help button on the CMake GUI.
       For full logs, run 'nix log /nix/store/4fvp4aqkjx882blhbrllvmljqzv3rz1f-workspace-deps-deps-0.0.1.drv'.
error: 1 dependencies of derivation '/nix/store/b88mh6xijxj1i3mp3y52bjhar3hly449-workspace-build-0.0.1.drv' failed to build
```

**Comment by ipetkov** [comment]
@rushmorem I believe the stdenv from nixpkgs [will automatically run cmake](https://nixos.org/manual/nixpkgs/unstable/#cmake) if it is present as a convenience for projects which require it, and setting `dontUseCmakeConfigure = true;` disables this behavior

**Comment by rushmorem** [comment]
@ipetkov You are right. Thank you for pointing that out. I see Naersk is doing that (https://github.com/nix-community/naersk/blob/6944160c19cb591eb85bbf9b2f2768a935623ed3/build.nix#L116), which is why it just works. Would it make sense to do the same for `Crane`? I don't suppose many Cargo projects use `cmake` directly.

**Comment by dpc** [comment]
I find the underlying behavior of calling `cmake` based on `buildInputs` wrong, because it's over-assuming. A composite project might need a `cmake` because some underlying piece needs it, and it's not an far fetched or rare. The whole thing should be opt-in. I would understand if `cmake` was called based on `CMakeLists` being present" but not on `buildInputs`...

**Comment by ipetkov** [comment]
The real issue is that [`cmake` comes with some setup hooks in nixpkgs](https://github.com/NixOS/nixpkgs/blob/b515e72bd7e9613021d62f7604c43e3d9efaf051/pkgs/development/tools/build-managers/cmake/setup-hook.sh) which injects this behavior by default. I agree its over-assuming, though at this rate it may not be possible to disable upstream because too many packages depend on it :(

**Comment by ipetkov** [comment]
Actually another way around this could be to [set our own empty configurePhase](https://github.com/NixOS/nixpkgs/blob/b515e72bd7e9613021d62f7604c43e3d9efaf051/pkgs/development/tools/build-managers/cmake/setup-hook.sh#L136). Callers can still expressly inject whatever configure phases they want (including `cmakeConfigurePhase` if they desire)

This might be a more elegant approach than using `dontUseCmakeConfigure`. Let me think about it a bit more when I get some free time
