### ISSUE TITLE
Unknown libc native/impure

### ISSUE THREAD

**Issue by rushmorem** [ipetkov/crane#112]
Setting `crossSystem` to `x86_64-windows` and running `nix flake check` fails with `error: Unknown libc native/impure`.

```diff
--- a/flake.nix
+++ b/flake.nix
@@ -16,7 +16,8 @@
     flake-utils.lib.eachDefaultSystem (system:
       let
         pkgs = import nixpkgs {
-          inherit system;
+          localSystem = system;
+          crossSystem = "x86_64-windows";
         };
 
         craneLib = crane.lib.${system};
```

Edit: It's very likely that this issue is not directly introduced by Crane.

**Comment by dpc** [comment]
We've just got bunch of stuff to cross compile for Wasm and Android from Nix:

* https://github.com/futurepaul/fluttermint/pull/64
* https://github.com/fedimint/fedimint/pull/610

So I'm not sure if there's a point trying to use crossSystem for Rust with crane.

**Comment by rushmorem** [comment]
> I'm not sure if using crossSystem for Rust with crane is a best way

I tried `crossSystem` first because that's how it's done in the `cross-rust-overlay` example. I did manage to sidestep this issue by using `fenix` instead and following `naersk`'s example. Though I did manage to get past that error, I still haven't managed to successfully cross-compile using Crane yet, even the `musl` derivation that's working on `naersk`, so thank you for those pull requests. I will take a look.

**Comment by rushmorem** [comment]
> It's very likely that this issue is not directly introduced by Crane.

This seems to be coming from Nix itself. I can reproduce it with just this:-

```nix
{
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";

  outputs = { self, nixpkgs, ... }:
    let
      pkgs = import nixpkgs {
        localSystem = "x86_64-linux";
        crossSystem = "x86_64-windows";
      };

    in { packages.x86_64-linux.default = pkgs.hello; };
}
```
