### ISSUE TITLE
Build scripts may not play nicely with dummy sources

### ISSUE THREAD

**Issue by ipetkov** [ipetkov/crane#117]
### Discussed in https://github.com/ipetkov/crane/discussions/115

Seems like cargo may be looking at the timestamp of the build script (or at the timestamp of the artifacts) to determine when it is being run. Since nix strips out the timestamps, cargo may not be (re)running the actual build script with the real files.

One potential solution is to make the dummy build script have a unique name (i.e. not `build.rs` and not whatever build script the Cargo.toml file may set), though I'm not sure what implications this may have on build artifact caching, if any

**Comment by dpc** [comment]
> I'm not sure what implications this may have on build artifact caching, if any

Now that I think about it - why does `crane` even produce fake `build.rs` scripts in `dummySrc`?

**Comment by ipetkov** [comment]
> why does crane even produce fake build.rs scripts in dummySrc?

To get cargo to build any `build-dependencies` so we can cache their artifacts
