### ISSUE TITLE
Undocumented(?) edge cases updating Cargo.toml / Cargo.lock

### ISSUE THREAD

**Issue by tv42** [ipetkov/crane#124]
Hi. I'm using https://github.com/rust-lang/mdBook and https://github.com/daviddrysdale/mdbook-indexing on a project, and wanted to build newer versions because of both 1) bugfixes and 2) nixpkgs seemed to have mismatching versions.

So mdbook has this slightly cumbersome design where preprocessors are supposed to be built against the version of mdbook that actually calls them (as subprocesses).

So, I'm looking at mdbook-indexing and trying to bump its dependencies to `mdbook = 0.4.21`. This is a "user confusion report", where I think crane is at least missing documentation, and might actually want to do things differently with regard to Cargo.lock.

mdbook-indexing commit e8e8cde3aabc1db3a83fd20d29dc827f0bdfbcd7 has

Cargo.toml: `mdbook = "0.4.*"`

https://github.com/daviddrysdale/mdbook-indexing/blob/e8e8cde3aabc1db3a83fd20d29dc827f0bdfbcd7/Cargo.toml#L17

Cargo.lock: `name = "mdbook"; version = "0.4.18"`

https://github.com/daviddrysdale/mdbook-indexing/blob/e8e8cde3aabc1db3a83fd20d29dc827f0bdfbcd7/Cargo.lock#L801-L803

What I wanted to make happen is essentially `cargo update -p mdbook --precise 0.4.21` in mdbook-indexing source tree, and then build that.

Attempt 1: clone mdbook-indexing, `cargo update -p mdbook --precise 0.4.21`, update mdbook dependency, make a patch containing Cargo.lock change, add to `crane.lib.${system}.buildPackage { ...; patches = [ ... ] }`. Building that made cargo complain:

```
++ command cargo check --profile release --all-targets
error: failed to select a version for the requirement `mdbook = "0.4.*"`
candidate versions found which didn't match: 0.4.18
```

The error message is slightly misleading, since both 0.4.18 and 0.4.21 would match that wildcard.
What I think is happening here is that crane is only offering mdbook v0.4.18 to cargo, and cargo is saying that lock file told it to use 0.4.21, which wasn't available -- and failing to include the relevant detail.

Attempt 2: same as above, but also patch Cargo.toml to have `mdbook = 0.4.21`. Didn't help, same error except for `error: failed to select a version for the requirement `mdbook = "^0.4.21"``

Attempt 3: pass updated Cargo.lock file via `cargoLock`. This might be broken due to the wildcard dependency use in mdbook-indexing, and not be crane's fault at all. Wildcards are pretty rare, I've never seen them in any project. Anyway:

```
crane.lib.${system}.buildPackage {
            src = inputs.mdbook-indexing;
            cargoLock = ./mdbook-indexing-cargo-lock-with-mdbook-0_4_21.toml;
};
```

```
++ command cargo build --profile release --message-format json-render-diagnostics
error: failed to select a version for the requirement `mdbook = "0.4.*"`
candidate versions found which didn't match: 0.4.21
```

Attempt 4:  Patch Cargo.toml to remove wildcard, pass Cargo.lock via `cargoLock` -- WORKS

```
crane.lib.${system}.buildPackage {
            src = inputs.mdbook-indexing;
            patches = [
              # changes Cargo.toml to say `mdbook = "0.4.21"`
              ./mdbook-indexing-e8e8cd-depend-mdbook-0_4_21.patch
            ];
            cargoLock = ./mdbook-indexing-cargo-lock-with-mdbook-0_4_21.toml;
};
```

I felt like this was quite unintuitive.

I would have expected crane to pick up Cargo.lock *after* patches.

**Comment by ipetkov** [comment]
Thank you for the report!

Currently traveling, will take a closer look at improving the documentation when I’m back. The crux of the issue is that crates are censored at _evaluation_ time and not at build time. That means if the Cargo.lock is patched as part of the build itself then we have no way of knowing what crates need vendoring ahead of time. 

It should be possible to work around this by patching the Cargo.lock in a stand-alone derivation, then passing the result into `vendorCargoDeps` (might need IFD enabled for non-flake configurations).

**Comment by tv42** [comment]
If I'm maintaining a patch on Cargo.lock, I might as well just keep a copy of the desired Cargo.lock outside; `cargoLock` works fine. But discovering all that was an "unexpected journey". Thanks again!

**Comment by ipetkov** [comment]
@tv42 I've opened #129 to add a comment about this scenario in the README, let me know if you have other suggestions or improvements to the docs!
