### ISSUE TITLE
Derivation version is incorrect when inheriting package metadata in workspaces

### ISSUE THREAD

**Issue by jessestricker** [ipetkov/crane#143]
I have a Cargo workspace where the member packages inherit their metadata from the workspace.
This feature was recently added in [v1.64](https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-164-2022-09-22).

A minimal version could look like this:

_`Cargo.toml`_

```toml
[workspace]
member = ["foo"]

[workspace.package]
version = "0.1.0"
```

_`foo/Cargo.toml`_

```toml
[package]
name = "foo"
version.workspace = true
```

When building, the derivation name is incorrect (too generic):

_`flake.nix`_

```nix
{
  outputs = inputs: {
    # ...
    packages.${system}.foo = craneLib.buildPackage {
      src = craneLib.cleanCargoSource ./.;
    };
  };
}
```

```console
$ nix build .#foo
$ ll result
result -> /nix/store/...-cargo-package-0.0.1
```

If I try to use the sub-directory as the source, it doesn't even evaluate:

_`flake.nix`_

```nix
{
  outputs = inputs: {
    # ...
    packages.${system}.foo = craneLib.buildPackage {
      src = craneLib.cleanCargoSource ./foo;
    };
  };
}
```

```console
$ nix build .#foo
error: cannot coerce a set to a string

       at /nix/store/drpbiq5h9k4549gvwz3xyh9v0ckjb67q-source/pkgs/stdenv/generic/make-derivation.nix:290:60:

          289|           then attrs.name + hostSuffix
          290|           else "${attrs.pname}${staticMarker}${hostSuffix}-${attrs.version}"
             |                                                            ^
          291|         );
```

I suspect the issue has something to do with the default `pname` and `version` attributes for `craneLib.cargoBuild`
coming from `craneLib.crateNameFromCargoToml`, which returns the following:

_`flake.nix`_

```nix
{
  outputs = inputs: {
    # ...
    foo = craneLib.crateNameFromCargoToml {
      cargoToml = ./foo/Cargo.toml;
    };
  };
}
```

```console
$ nix eval .#foo
{ pname = "foo"; version = { workspace = true; }; }
```

_(I would have expected it to return `{ pname = "foo"; version = "0.1.0"; }`.)_

**Comment by jessestricker** [comment]
I should also note that my actual Cargo workspace is _virtual__ and that there are other member packages, but they all contain library targets exclusively. 
The `foo` package is the only one providing a binary target.

**Comment by ipetkov** [comment]
Thanks for the report @jessestricker !

> When building, the derivation name is incorrect (too generic):

Unfortunately cargo doesn't have the concept of a "workspace name" so there isn't much we can do to infer what the Nix derivation should be called if the source being built is a workspace (though we will infer it if the root is a regular Cargo package definition). I would recommend explicitly setting `pname = "..."` in the derivation with a name of your choosing to avoid the generic `cargo-package` naming.

> I suspect the issue has something to do with the default pname and version attributes for craneLib.cargoBuild
coming from craneLib.crateNameFromCargoToml, which returns the following:
> (I would have expected it to return { pname = "foo"; version = "0.1.0"; }.)

Yes `crateNameFromCargoToml` did not take the possibility of inheriting the version from the workspace definition. I've opened #144 to fix this!
