### ISSUE TITLE
Easier way to lock unlocked dependencies; vendor crates from flake inputs

### ISSUE THREAD

**Issue by tv42** [ipetkov/crane#149]
I tried to build <https://github.com/DioxusLabs/cli>, rev 3bac1ac1a7062fdcbb31a9f967e0acd8703235ac.

It has Cargo.toml https://github.com/DioxusLabs/cli/blob/3bac1ac1a7062fdcbb31a9f967e0acd8703235ac/Cargo.toml#L57-L58

```
dioxus-core = { git = "https://github.com/dioxuslabs/dioxus/", features = ["hot-reload"] }
dioxus-rsx = { git = "https://github.com/dioxuslabs/dioxus/", features = ["hot-reload"] }
```

That is, fetch the latest every time. Nothing in Cargo.lock. Building that fails with

```
warning: spurious network error (2 tries remaining): failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
warning: spurious network error (1 tries remaining): failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
error: failed to get `dioxus-core` as a dependency of package `dioxus-cli v0.1.5 (/build/dummy-src)`
```

I think I could work around this by patching Cargo.toml and Cargo.lock (like in #124), but that's a pain to keep up to date.

I wish there was a way to take a flake input `dioxus = { url = "github:DioxusLabs/dioxus"; flake = false; };` and feed that into the build as a vendored crate(s). In this case, cargo shouldn't care about the exact version being vendored.

(Related, lib.downloadCargoPackageFromGit kinda sounds like it should just be a flake input. Of course, it probably has an internal use -- but external callers would likely be better off with flake inputs, with updating etc.)

My build error is similar to #142, but triggered by different circumstances.

**Comment by tv42** [comment]
Oh yes, I didn't think of transitive dependencies.

Maybe something like run `cargo update` or friends outside of the nix sandbox, then record the results of *that*. Better than maintaining a textual patch of Cargo.lock. But I guess at that point what I really have is a git fork of the repo with the problematic Cargo.toml/Cargo.lock.

**Comment by ipetkov** [comment]
> Maybe something like run cargo update or friends outside of the nix sandbox, then record the results of that

Yeah unfortunately this looks like the only solution in the general sense. I took a closer look at the repo you linked and it does look like they have a `Cargo.lock` file commit to the repository, but for some reason it is missing entries for the git repos. Even if we vendored the crates.io index locally it won't help with resolving the actual repos themselves (unless you disable the sandbox, at which point you might as well automate the updates outside of the Nix definition too...)

> But I guess at that point what I really have is a git fork of the repo with the problematic Cargo.toml/Cargo.lock.

Have you considered sending an upstream PR to update the `Cargo.lock` file? Running something like `cargo outdated` will make sure the lock file has no missing dependencies without updating anything in case the project doesn't want to run `cargo update`. If the project wants their CI to always build with the latest commits of their repos they can always run `cargo update -p THEIR_CRATE` without forcing a broken `Cargo.lock` downstream...

I am sympathetic to adding helpers within Crane where possible but I'm not sure there is much we can do downstream of this situation (e.g. even if we were to crawl all git repo URLs we still need to tell Nix what revision to check out) :disappointed:

**Comment by tv42** [comment]
The case with that repository is that they're in heavy early development, so I don't think they want to be bothered with bumping the version yet.

I didn't think of the transitive dependencies, that complicates things for sure.

Maybe this is better closed. Time will heal this hurt, as that project matures.

**Comment by ipetkov** [comment]
Do feel free to open an issue or discussion if you happen to have other improvement ideas!
