### ISSUE TITLE
error[E0433]: failed to resolve: maybe a missing crate `core`?

### ISSUE THREAD

**Issue by henriiik** [ipetkov/crane#163]
Hello!

Thank you for a good library, especially the docs are very good and helpful!

I am new to nix, so maybe i am doing something strange, but when i added a workspace-hack crate to my workspace (with [cargo-hakari](https://crates.io/crates/cargo-hakari) i started getting errors like this when building with `crane`:

```
error[E0433]: failed to resolve: maybe a missing crate `core`?
 --> /nix/store/isp0cn038bjjkscz1ms7cf4z80gbd5k0-dummy.rs:5:20
  |
5 | fn panic(_info: &::core::panic::PanicInfo<'_>) -> ! {
  |                    ^^^^ maybe a missing crate `core`?
  |
  = help: consider adding `extern crate core` to use the `core` crate
 
For more information about this error, try `rustc --explain E0433`.
```

I added `extern crate core;` to the `dummy.rs` template, it started working again: https://github.com/henriiik/crane/commit/5e855b76516730bf265843f4adc28cbb72944ed2

Would you be interested in upstreaming something like this? If so i can make a proper PR.

**Comment by ipetkov** [comment]
Hi @henriiik thanks for the report!

I do believe we have a test case for this but maybe the cfgs in our dummy.rs script are missing something? Or maybe cargo-hakari is tickling the gap in some way?

Either way I would accept a PR to add `extern crate core` in there, I can't think of a reason why including it would break anything else 😃

**Comment by henriiik** [comment]
Thank you @ipetkov for implementing this! 🙏

I updated my project to use the latest master and it works! 🎉
