### ISSUE TITLE
`remove-references-to` for split debug info

### ISSUE THREAD

**Issue by dpc** [ipetkov/crane#164]
This is side tracking from #161 just not keep the conversation tidy.

In recent Rust version an option to move debug symbols to sperate files were introduced. I wonder if `remove-references-to` knows to take care of them as well.

**Comment by ipetkov** [comment]
Currently we do [check all files in the installation directory](https://github.com/ipetkov/crane/blob/074825a9e8d6446564e2ae6949ac3feb79aa7397/lib/setupHooks/removeReferencesToVendoredSourcesHook.sh#L27) so in theory they should be taken care of
