### ISSUE TITLE
Can't Build x86_64-unknown-uefi Application

### ISSUE THREAD

**Issue by blitz** [ipetkov/crane#173]
I'm trying to migrate a UEFI application from naersk to crane and am hitting issues. The problem is this:

```
initrd-stub-deps>     Checking uefi v0.18.0
initrd-stub-deps> error[E0463]: can't find crate for `std`
initrd-stub-deps>   |
initrd-stub-deps>   = note: the `x86_64-unknown-uefi` target may not support the standard library
initrd-stub-deps>   = note: `std` is required by `initrd_stub` because it does not declare `#![no_std]`
initrd-stub-deps>   = help: consider building the standard library from source with `cargo build -Zbuild-std`
initrd-stub-deps> error[E0463]: can't find crate for `test`
initrd-stub-deps> error: `#[panic_handler]` function required, but not found
initrd-stub-deps> For more information about this error, try `rustc --explain E0463`.
initrd-stub-deps> error: could not compile `initrd-stub` due to 3 previous errors
```

This is weird, because this _is_ actually a `no_std` application. This can be reproduced using: `nix -L build github:blitz/lanzaboote/crane-uefi#initrd-stub`. The corresponding code is [here](https://github.com/blitz/lanzaboote/blob/crane-uefi/flake.nix#L55).

The corresponding build with naersk is successful: `nix -L build github:blitz/lanzaboote/crane-uefi#initrd-stub-naersk`.

Any hints are appreciated! This also looks similar to #127.

**Comment by ipetkov** [comment]
Hi @blitz thanks for the report!

It looks like `rustc +nightly -Z unstable-options --print cfg --target x86_64-unknown-uefi` reports that the `target_os` cfg is set to "uefi" while [the dummy source we create](https://github.com/ipetkov/crane/blob/c61d98aaea5667607a36bafe5a6fa87fe5bb2c7e/lib/mkDummySrc.nix#L124) is checking that `target_os = "none"`

This should be fixed with #174!

**Comment by blitz** [comment]
Thanks for the fast fix! Will verify asap. :+1:

**Comment by blitz** [comment]
> Thanks for the fast fix! Will verify asap. +1

Works! Thanks you very much! :tada:
