### ISSUE TITLE
API doc mentions `cleanSourcesFilter`, did you mean `cleanSource` or `cleanSourceWith`?

### ISSUE THREAD

**Issue by sir4ur0n** [ipetkov/crane#176]
I was reading through https://github.com/ipetkov/crane/blob/master/docs/API.md#libcleancargosource trying to figure out how to include `*.lalrpop` files into my build, and I noticed the doc mentions `cleanSourcesFilter` but this does not exist in Nixpkgs nor in Crane code.

In Crane code, the only similar Nix code used is:
* `cleanSourceWith`
* `cleanSource` (which is just a special case of `cleanSourceWith`)

In Nixpkgs, there exists a function `cleanSourceFilter` (notice the singular `Source`), but it does not appear to be directly used by Crane code.

**Comment by ipetkov** [comment]
Ah, thanks for the report @sir4ur0n! Yes this is a typo, `cleanCargoSource` will internally use `cleanSource` so I'll update the docs to correct the name!
