### ISSUE TITLE
Trouble building a project with bindgen/cmake

### ISSUE THREAD

**Issue by forficate** [ipetkov/crane#188]
I'm trying to build a project that depends on the high-sys crate. Using crane I get the below error:

```
--- stderr
  CMake Error: The current CMakeCache.txt directory /build/source/target/release/build/highs-sys-7473b6736d4fd4df/out/build/CMakeCache.txt is different than the directory /build/dummy-src/target/release/build/highs-sys-7473b6736d4fd4df/out/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 1
```

From the error message it looks like `/build/dummy-src/target/release/build/highs-sys-7473b6736d4fd4df/` is copied to `/build/source/target/release/build/highs-sys-7473b6736d4fd4df` and rebuilt? Based on the error message the `out/build` directory should be excluded in the copy?

**Comment by ipetkov** [comment]
Hi @forficate thanks for the report!

Looks like cmake expects the path where it is being built to not change, but the dummy sources are unpacked to `/build/dummy-src/` instead of `/build/source/`. Should be fixed with #190
