### ISSUE TITLE
Handling source-adjacent packages?

### ISSUE THREAD

**Issue by mstone** [ipetkov/crane#19]
Do you have any advice on how to handle the situation of "a source control repo that contains a library package at the repo root + multiple binary packages in subdirectories", where the binary packages depend on crates defined in the library package, often referenced via relative paths in Cargo.toml?

(Here, I am specifically interested in using `crane` to write a flake that exposes outputs for the binary packages -- e.g., a web server, a wasm frontend, and some platform-specific GUI clients.)

Thanks! (and thanks also for writing and publishing `crane`; it looks like a lovely addition to the nix + rust ecosystem!)

**Comment by ipetkov** [comment]
Hi @mstone, thank you for the kind words!

Philosophically, Crane aims to be a thin wrapper around cargo to bridge any gaps with Nix. Besides that it should be possible to configure the derivation to invoke whatever cargo commands you'd use to build the project even outside of Nix.

Is the project in question all one big cargo workspace? By default Crane will build all binaries in the workspace, but you can override the cargo build flags to specify only one specific binary like so:

```nix
let
  src = ./src;
  # Build workspace artifacts (and cache the evaluation)
  cargoArtifacts = crane.buildDepsOnly {
    inherit src;
  };
in
{
  myBin = crane.buildPackage {
    inherit src cargoArtifacts;
    cargoBuildCommand = "cargo build --release --bin myBin";
  };

  myOtherBin = crane.buildPackage {
    inherit src cargoArtifacts;
    cargoBuildCommand = "cargo build --release --bin myOtherBin";
  };
}
```

If the project is modeled as multiple, distinct cargo-workspaces, there may need to be more configuration steps (e.g. to point cargo to the right place, or get everything vendored appropriately, etc.), but I can't speak much more about it without looking at a concrete example.

Does this help?

**Comment by mstone** [comment]
It does help, both to hear this description of the philosophy behind `crane` and to see from your reply the crucial `cargoArtifacts` argument that I had been neglecting to set in my calls to `crane.buildPackage` -- thanks!
