### ISSUE TITLE
Document how to handle Workspaces

### ISSUE THREAD

**Issue by DrRuhe** [ipetkov/crane#197]
### Discussed in https://github.com/ipetkov/crane/discussions/189

Here is some writeup of what I found out:

# Cargo Workspaces
Workspaces with multiple members are supported. The examples build everything in the workspace by default, similar as to how `cargo build` will try to build everything in the workspace by default. 

## Building Binaries in a Workspace
Binaries in a workspace can be built by adding a `--bin` flag to the `cargoExtraArgs` and setting the `pname` like this:
```nix
my-bin = craneLib.buildPackage {
    inherit cargoArtifacts src buildInputs;
    pname = "my-bin";
    cargoExtraArgs = "--bin my-bin";
};
```

**Comment by ipetkov** [comment]
Thanks for the suggestion @DrRuhe, I've opened #198 to add this to the README!
