### ISSUE TITLE
Issues with Wasm artifacts produced by `crane`

### ISSUE THREAD

**Issue by paulyoung** [ipetkov/crane#207]
I'd been using `naersk` for a while and at some point switched everything but one package over to using `crane`.

That one package is targeting `wasm32-unknown-unknown` and, for some reason, produces Wasm artifacts that are somehow missing something.

For example, some automated reporting that I set up using `twiggy` fails with `error: function or code section is missing` which might originate [here](https://github.com/rustwasm/twiggy/blob/628a8ce0d7c887d44f1f25823b238bc2f28058c9/parser/wasm_parse/mod.rs#L147) or [here](https://github.com/rustwasm/twiggy/blob/628a8ce0d7c887d44f1f25823b238bc2f28058c9/parser/wasm_parse/mod.rs#L330).

`twiggy --version` outputs `twiggy-opt 0.7.0`

***

If I bypass those `twiggy` commands, I get to my optimization phase which reduces the `.wasm` file from `1780085` to `83` bytes. With `naersk` these numbers are `5854784` and `2818287` respectively.

***

I also use `wasm-objdump` to output information. With `naersk` it looks like this:

```
wasm-objdump -h:
myproject.wasm:  file format wasm 0x1
Sections:
     Type start=0x0000000e end=0x000002ba (size=0x000002ac) count: 79
   Import start=0x000002c0 end=0x000003fc (size=0x0000013c) count: 16
 Function start=0x00000402 end=0x00002c77 (size=0x00002875) count: 10355
    Table start=0x00002c7d end=0x00002c84 (size=0x00000007) count: 1
   Memory start=0x00002c8a end=0x00002c8d (size=0x00000003) count: 1
   Global start=0x00002c93 end=0x00002cac (size=0x00000019) count: 3
   Export start=0x00002cb2 end=0x00002f38 (size=0x00000286) count: 19
     Elem start=0x00002f3e end=0x00003804 (size=0x000008c6) count: 1
     Code start=0x0000380a end=0x00204677 (size=0x00200e6d) count: 10355
     Data start=0x0020467d end=0x002b00ef (size=0x000aba72) count: 2
```

With `crane` it looks like this:

```
wasm-objdump -h:
myproject.wasm:   file format wasm 0x1
Sections:
   Memory start=0x0000000e end=0x00000011 (size=0x00000003) count: 1
   Global start=0x00000017 end=0x00000028 (size=0x00000011) count: 2
   Export start=0x0000002e end=0x00000053 (size=0x00000025) count: 3
```

***

If I bypass the optimization (which is obviously stripping out most of the file because it thinks it's unused) things look like this:

With `naersk`:

```
wasm-objdump -h:
myproject.wasm:  file format wasm 0x1
Sections:
     Type start=0x0000000b end=0x000002b7 (size=0x000002ac) count: 79
   Import start=0x000002ba end=0x000003f6 (size=0x0000013c) count: 16
 Function start=0x000003f9 end=0x00002c6e (size=0x00002875) count: 10355
    Table start=0x00002c70 end=0x00002c77 (size=0x00000007) count: 1
   Memory start=0x00002c79 end=0x00002c7c (size=0x00000003) count: 1
   Global start=0x00002c7e end=0x00002c97 (size=0x00000019) count: 3
   Export start=0x00002c9a end=0x00002f20 (size=0x00000286) count: 19
     Elem start=0x00002f23 end=0x000037ea (size=0x000008c7) count: 1
     Code start=0x000037ef end=0x00238acb (size=0x002352dc) count: 10355
     Data start=0x00238acf end=0x002e4541 (size=0x000aba72) count: 2
   Custom start=0x002e4545 end=0x003482ba (size=0x00063d75) ".debug_info"
   Custom start=0x003482bd end=0x003484fb (size=0x0000023e) ".debug_pubtypes"
   Custom start=0x003484ff end=0x003734ed (size=0x0002afee) ".debug_ranges"
   Custom start=0x003734f0 end=0x00374ba3 (size=0x000016b3) ".debug_abbrev"
   Custom start=0x00374ba7 end=0x003bbbb1 (size=0x0004700a) ".debug_line"
   Custom start=0x003bbbb5 end=0x0045c450 (size=0x000a089b) ".debug_str"
   Custom start=0x0045c454 end=0x0049b33a (size=0x0003eee6) ".debug_pubnames"
   Custom start=0x0049b33e end=0x005955e9 (size=0x000fa2ab) "name"
   Custom start=0x005955eb end=0x00595640 (size=0x00000055) "producers"
```

With `crane`:

```
wasm-objdump -h:
myproject.wasm:   file format wasm 0x1
Sections:
    Table start=0x0000000a end=0x0000000f (size=0x00000005) count: 1
   Memory start=0x00000011 end=0x00000014 (size=0x00000003) count: 1
   Global start=0x00000016 end=0x0000002f (size=0x00000019) count: 3
   Export start=0x00000031 end=0x00000056 (size=0x00000025) count: 3
   Custom start=0x0000005a end=0x00062d6f (size=0x00062d15) ".debug_info"
   Custom start=0x00062d72 end=0x00062ec6 (size=0x00000154) ".debug_pubtypes"
   Custom start=0x00062eca end=0x0008de58 (size=0x0002af8e) ".debug_ranges"
   Custom start=0x0008de5b end=0x0008eebe (size=0x00001063) ".debug_abbrev"
   Custom start=0x0008eec2 end=0x000d4beb (size=0x00045d29) ".debug_line"
   Custom start=0x000d4bef end=0x00174397 (size=0x0009f7a8) ".debug_str"
   Custom start=0x0017439b end=0x001b2903 (size=0x0003e568) ".debug_pubnames"
   Custom start=0x001b2905 end=0x001b291e (size=0x00000019) "name"
   Custom start=0x001b2920 end=0x001b2975 (size=0x00000055) "producers"
```

As `twiggy` said, the `Function` and `Code` sections are missing.

***

I ran into this months ago and didn't have time to investigate but now have some additional motivation for moving to `crane`.

I'm assuming it's something trivial like an entry point isn't being exported. I haven't starting looking into this yet but appreciate any advice on how to get started.

**Comment by paulyoung** [comment]
I just noticed that the output I shared above is prefixed with `rust-workspace-unknown>` when using `naersk` but `myproject-deps>` when using `crane`.

Does this mean the `.wasm` file only contains dependencies?

**Comment by paulyoung** [comment]
Perhaps important: my `Cargo.toml` is configured like this:

```toml
[lib]
# rlib due to: https://github.com/rust-lang/cargo/issues/6659
crate-type = ["cdylib", "rlib"]
```

Maybe I need to use `[[bin]]`?

**Comment by paulyoung** [comment]
Then I would need to use `#[main]` to indicate the entry point which doesn't make sense for my Wasm module and would probably result in some code paths being removed anyway.

**Comment by paulyoung** [comment]
Maybe using `[[bin]]`, setting `name = "..."`, and adding `main() {}` is sort of a step in the right direction.

As I suspected though, the optimizer is removing almost everything since it's not touched by `main`.

**Comment by paulyoung** [comment]
I think maybe all I need to do here is make sure the functions I'm exporting in `main.rs` are public with `pub`.

**Comment by paulyoung** [comment]
That didn't work unfortunately.

**Comment by paulyoung** [comment]
It looks like the optimizer I'm using is supposed to cover this use case and I may have found a bug.

In any case, I think this answers why I was seeing strange Wasm artifacts being produced (using `lib`) but perhaps `crane` could support that and behave the way `naersk` does?

**Comment by paulyoung** [comment]
> It looks like the optimizer I'm using is supposed to cover this use case and I may have found a bug.

Hmm, perhaps not. This is the output of `wasm-objdump` without the optimizer applied:

```
wasm-objdump -h:
myproject.wasm:   file format wasm 0x1
Sections:
     Type start=0x0000000a end=0x00000052 (size=0x00000048) count: 12
 Function start=0x00000054 end=0x00000087 (size=0x00000033) count: 50
    Table start=0x00000089 end=0x0000008e (size=0x00000005) count: 1
   Memory start=0x00000090 end=0x00000093 (size=0x00000003) count: 1
   Global start=0x00000095 end=0x000000ae (size=0x00000019) count: 3
   Export start=0x000000b0 end=0x000000dc (size=0x0000002c) count: 4
     Elem start=0x000000de end=0x000000f5 (size=0x00000017) count: 1
     Code start=0x000000f8 end=0x00003e9b (size=0x00003da3) count: 50
     Data start=0x00003e9e end=0x000045fc (size=0x0000075e) count: 1
   Custom start=0x00004600 end=0x0000ab4f (size=0x0000654f) ".debug_info"
   Custom start=0x0000ab51 end=0x0000aba9 (size=0x00000058) ".debug_pubtypes"
   Custom start=0x0000abac end=0x0000c702 (size=0x00001b56) ".debug_ranges"
   Custom start=0x0000c705 end=0x0000caf9 (size=0x000003f4) ".debug_abbrev"
   Custom start=0x0000cafc end=0x000105e7 (size=0x00003aeb) ".debug_line"
   Custom start=0x000105eb end=0x0001dc63 (size=0x0000d678) ".debug_str"
   Custom start=0x0001dc67 end=0x00023d14 (size=0x000060ad) ".debug_pubnames"
   Custom start=0x00023d17 end=0x00024ac9 (size=0x00000db2) "name"
   Custom start=0x00024acb end=0x00024b20 (size=0x00000055) "producers"
```

**Comment by paulyoung** [comment]
Just to confirm, I switched back to the `[lib]` configuration to see if the issue was that before I hadn't made any of the exported functions public but that has made no difference.

**Comment by dpc** [comment]
Please link nix code.

**Comment by paulyoung** [comment]
Please see https://github.com/paulyoung/crane-wasm-issue

**Comment by paulyoung** [comment]
It looks like building with `--bin` may be the solution: https://github.com/paulyoung/crane-wasm-issue/commit/6953a1f22991bbdfcceba784e3a24f4db5a26a70

**Comment by paulyoung** [comment]
`--lib` also fixes things for libraries.

**Comment by paulyoung** [comment]
This is really strange. The same thing doesn't work in my actual project.

**Comment by paulyoung** [comment]
To clarify; "doesn't work" means that `twiggy` fails in the `postDist` phase of `-deps` due to missing sections.

**Comment by paulyoung** [comment]
I think the real problem is that my `postDist` phase is designed for `mypackage` but it's being run on `mypackage-deps`.

**Comment by paulyoung** [comment]
I'm now using a separate derivation and `buildDepsOnly` to avoid this.

**Comment by dpc** [comment]
> I'm now using a separate derivation and `buildDepsOnly` to avoid this.

This might be the problem.
If you don't specify `cargoArtifacts` explicitly, then `crane` will infer some in some ways that might be completely wrong for what you're trying to do with this complex building procedure.

https://github.com/ipetkov/crane/blob/master/docs/API.md#optional-attributes-1

**Comment by paulyoung** [comment]
Now that this is working I wanted to summarize what I think I've learned.

* `--lib` or `--bin` is required when targeting Wasm, otherwise only the `-deps` derivation is built (as evidenced by https://github.com/paulyoung/crane-wasm-issue/commit/006cc94eaa4f7c76da4bfa6d5943018273f005c4 and https://github.com/paulyoung/crane-wasm-issue/commit/6953a1f22991bbdfcceba784e3a24f4db5a26a70)
* Unless `cargoArtifacts` is specified, `distPhase` (and other phases) will also run on the `-deps` derivation which most likely doesn't make sense.

I'm happy to close this issue but not sure if it warrants some updated documentation.

The `custom-toolchain` example may also be affected by this but I don't know much about targeting WASI.

**Comment by dpc** [comment]
You probably do want to create `-deps` derivation yourself BTW. It will save you needless rebuilds of all dependencies each time your change any file. However the implicit one that crane is creating for you is probably not doing the right thing.

**Comment by ipetkov** [comment]
Here's something I noticed: the flake sets `cargoExtraArgs = "--package ${pname}";` but also sets `cargoBuildCommand = "cargoWithProfile build --lib --target wasm32-unknown-unknown";`. Keep in mind that the dependencies-only derivation runs `cargo check` and `cargo test`, none of which know about doing what target you want built.

My recommendation is to remove `cargoBuildCommand` entirely and change `cargoExtraArgs = "--package ${pname} --target wasm32-unknown-unknown";`. You'll likely also want to set `doCheck = false;` as cargo will fail to run the tests (assuming your runner does not have the ability to run wasm modules directly).

**Comment by paulyoung** [comment]
> You probably do want to create -deps derivation yourself BTW. It will save you needless rebuilds of all dependencies each time your change any file (solving this problem is kind of a main point of using crane). However the implicit one that crane is creating for you is probably not doing the right thing because you do require bunch of custom stuff.
>
> I think you need to better understand what crane is doing and then write your own deps-only derivation.

Yes, agreed. I thought this was an optimization and didn't know the implicit one was working the way it does. I think I got on the wrong track by following the the `custom-toolchain` example.

**Comment by paulyoung** [comment]
> Keep in mind that the dependencies-only derivation runs cargo check and cargo test, none of which know about doing what target you want built.

I didn't realize this. Thanks for pointing it out.

> My recommendation is to remove cargoBuildCommand entirely and change cargoExtraArgs = "--package ${pname} --target wasm32-unknown-unknown";. You'll likely also want to set doCheck = false; as cargo will fail to run the tests (assuming your runner does not have the ability to run wasm modules directly).

The motivation for using `cargoBuildCommand` is so that I can specify a Wasm target for builds but not for tests, since most tests aren't Wasm-specific and are still beneficial even if not using the same target.

**Comment by ipetkov** [comment]
> The motivation for using cargoBuildCommand is so that I can specify a Wasm target for builds but not for tests, since most tests aren't Wasm-specific and are still beneficial even if not using the same target.

I see, running the tests outside of wasm is definitely possible, though trying to do it all in a single derivation might be causing some confusion. You might want to separate them out into discrete derivations just to keep the configuration more straightforward. It is still possible to chain things together so you use the same caches if you wish. Here's a rough example:

```nix
let
  src = ./.;

  # Build the default deps for x86
  depsOnlyX86 = craneLib.buildDepsOnly {
    inherit src;
  };

  # Also build wasm deps
  depsOnlyX86AndWasm = craneLib.cargoBuild {
    # Still use the dummified source here to avoid rebuilds
    src = craneLib.mkDummySrc src;
    cargoArtifacts = depsOnlyX86;
    cargoExtraArgs = "--target wasm32-unknown-unknown";
  };

  # Actual wasm build
  myWasm = craneLib.cargoBuild {
    inherit src;
    cargoArtifacts = depsOnlyX86AndWasm;
    cargoExtraArgs = "--bin whatever --target wasm32-unknown-unknown";
  };
in
myWasm
```

**Comment by paulyoung** [comment]
> Now that this is working I wanted to summarize what I think I've learned.
>
> * `--lib` or `--bin` is required when targeting Wasm, otherwise only the `-deps` derivation is built (as evidenced by https://github.com/paulyoung/crane-wasm-issue/commit/006cc94eaa4f7c76da4bfa6d5943018273f005c4 and https://github.com/paulyoung/crane-wasm-issue/commit/6953a1f22991bbdfcceba784e3a24f4db5a26a70)
> * Unless `cargoArtifacts` is specified, `distPhase` (and other phases) will also run on the `-deps` derivation which most likely doesn't make sense.

For the sake of posterity, I believe this first point here is only true when not specifying `cargoArtifacts` which, for multiple reasons, is recommended anyway.

With that said I'm going to close this. Thanks all.
