### ISSUE TITLE
Superfluous `follows` in examples

### ISSUE THREAD

**Issue by pnotequalnp** [ipetkov/crane#21]
In the examples/templates, they all have this:
```nix
  {
    flake-utils = {
      url = "github:numtide/flake-utils";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  }
```
But `flake-utils` [doesn't have Nixpkgs as an input](https://github.com/numtide/flake-utils/blob/master/flake.nix#L3=), so the `follows` line is superfluous.

**Comment by ipetkov** [comment]
Great catch, thanks! This has been fixed in https://github.com/ipetkov/crane/commit/d3efda535f9216d02058104785a6d9cebf48eeb2
