### ISSUE TITLE
Add env vars to cargo build command

### ISSUE THREAD

**Issue by benwis** [ipetkov/crane#232]
I'm just getting started with crane and nix, so forgive me if I'm missing something but is there a way to set env vars and/or modify the cargo build command?
```nix
my-crate = craneLib.buildPackage {
inherit cargoArtifacts src buildInputs;
};
```
For the workspace I'm packaging, I'd like to set `SQLX_OFFLINE=true` so that crane/Nix doesn't try to look for a DB. Thanks!

**Comment by dpc** [comment]
My impression is that setting any capital-letters attribute will get it forwarded to `mkDerivation` which will set the env variable during build.

https://github.com/fedimint/fedimint/blob/75604eae4ce3589404e46446204d23cd6c3f329e/flake.nix#L328

**Comment by benwis** [comment]
That does seem to work as you describe, it'd be nice to have that in the docs somwhere. Thanks @dpc!

**Comment by dpc** [comment]
It might be already [documented](https://github.com/ipetkov/crane/blob/master/docs/API.md):

> In addition to all default and overridden values being set as documented below, all derivation attributes are delegated to mkCargoDerivation, and can be used to influence its behavior.

You just have to understand `mkCargoDerivation`, which is kind of a very core Nix primitive. but as a newcomers I wanted to use `crane` without being skilled with Nix much yet myself.

**Comment by ipetkov** [comment]
Hi @benwis thanks for the report!

As @dpc mentioned, `buildPackage` (along with `cargoBuild` and all other friends) all get lowered to `mkCargoDerivation` which largely delegates to `mkDerivation`.

`mkDerivation` comes from nixpkgs and comes with all the shell hooks for configuring and running the build. Any key-value pairs passed to it (and by extension passed to `buildPackage`, et al.) will automatically be set as environment variables for the build!

All you'd need to do is set
```nix
my-crate = craneLib.buildPackage {
  inherit cargoArtifacts src buildInputs;
  SQLX_OFFLINE = "true";
};
```

---
I've opened https://github.com/ipetkov/crane/pull/233 to improve the docs on this, but let me know if you'd like to suggest other improvements!
