### ISSUE TITLE
Can't overwrite `pnameSuffix` and `buildPhaseCargoCommand`

### ISSUE THREAD

**Issue by dpc** [ipetkov/crane#235]
I've noticed I can't overwrite the default suffix by setting `pnameSuffix`. Is this supposed to work this way?

In the code I see `(args // { pnameSuffix = "-deps" })` which suggest that the default always overwrites my settings. Shouldn't these two be reversed here and possibly many other places?

**Comment by dpc** [comment]
Seems like overwritting `buildPhaseCargoCommand` in `lib.cargoBuild` doesn't work as well, but it does work in `lib.buildDepsOnly`?

**Comment by ipetkov** [comment]
`pnameSuffix` is only used to construct the _name of the derivation_, which basically only affects the store path being something like `/nix/store/abc123-${name}-${pnameSuffix}`. It also makes it easy to spot what things are at a glance if you do a `nix build --dry-run`.

That said, `pnameSuffix` was not made to be configurable since it shouldn't affect anything meaningfully. Are you depending on the actual name of the derivation for anything? (I wouldn't recommend it if you are!)

**Comment by dpc** [comment]
> It also makes it easy to spot what things are at a glance if you do a `nix build --dry-run`.

That's exactly how I like it.

I have a `commonArgs` where I put `pname = "myproject"` and then I use it in many, many separate `lib.buildX` invocations, and would nice to be change just the suffix and not have to worry about it.

Though my biggest concern is not being able to overwrite `buildPhaseCargoCommand` in `lib.cargoBuild` actually. I thought these might be connected.

I have a:

```
        workspaceDepsCov = craneLib.buildDepsOnly (commonArgs // {
          pnameSuffix = "-lcov-deps";
          src = filterWorkspaceDepsBuildFiles ./.;
          buildPhaseCargoCommand = "cargo llvm-cov --workspace --profile $CARGO_PROFILE --no-report";
          cargoBuildCommand = "dontuse";
          cargoCheckCommand = "dontuse";
          nativeBuildInputs = commonArgs.nativeBuildInputs ++ [ cargo-llvm-cov ];
          doCheck = false;
        });

        workspaceCov = craneLib.cargoBuild (commonArgs // {
          pnameSuffix = "-lcov";
          cargoArtifacts = workspaceDepsCov;
          buildPhaseCargoCommand = "mkdir -p $out ; cargo llvm-cov --workspace --profile $CARGO_PROFILE --lcov --all-targets --test --output-path $out/lcov.info";
          nativeBuildInputs = commonArgs.nativeBuildInputs ++ [ cargo-llvm-cov ];
          doCheck = false;
        });
```

and it is not doing the right thing.

**Comment by ipetkov** [comment]
> I have a `commonArgs` where I put `pname = "myproject"` and then I use it in many, many separate `lib.buildX` invocations, and would nice to be change just the suffix and not have to worry about it.

The idea is that for the same package (say named "mycrate") you'd have a different prefix for building deps, for running clippy, etc. so you'd have `mycrate-deps`, `mycrate-clippy`, and so on. Setting the same `pnameSuffix` for all your crates would make them all have the exact same name (whether you are building deps, or the entire crate) so maybe I'm not understanding why that is useful :thinking: 

> Though my biggest concern is not being able to overwrite `buildPhaseCargoCommand` in `lib.cargoBuild` actually. I thought these might be connected.

[buildDepsOnly definitely prioritizes the passed in buildPhaseCargoCommand](https://github.com/ipetkov/crane/blob/8c34e5ecadc691dd64b31b9317eb35d7cdaa636b/lib/buildDepsOnly.nix#L46) so I'm not sure what the issue might be. All cargo invocations (including custom ones you are writing yourself) should get printed in the logs ([thanks to this helper function](https://github.com/ipetkov/crane/blob/8c34e5ecadc691dd64b31b9317eb35d7cdaa636b/lib/setupHooks/cargoHelperFunctionsHook.sh#L2-L8)) so I'd be curious to see what the logs are showing for that job.

I wonder if `cargo llvm-cov` itself isn't working for some reason??

**Comment by dpc** [comment]
> The idea is that for the same package (say named "mycrate") you'd have a different prefix for building deps, for running clippy, etc. so you'd have `mycrate-deps`, `mycrate-clippy`, and so on. Setting the same `pnameSuffix` for all your crates would make them all have the exact same name (whether you are building deps, or the entire crate) so maybe I'm not understanding why that is useful thinking

That's what I want to do. I just want to be able to set a custom suffix sometimes like `-lcov-deps`. And it doesn't work. It always uses the default corresponding to the `lib.cargoXyz` being used.

> [buildDepsOnly definitely prioritizes the passed in buildPhaseCargoCommand](https://github.com/ipetkov/crane/blob/8c34e5ecadc691dd64b31b9317eb35d7cdaa636b/lib/buildDepsOnly.nix#L46)

Sorry, I meant `cargoBuild`, and I just realized that I should probably just use `lib.buildPackage`.

https://github.com/ipetkov/crane/blob/98894bb39b03bfb379c5e10523cd61160e1ac782/lib/cargoBuild.nix#L17

**Comment by ipetkov** [comment]
Ah I understand, what you are looking for is using `mkCargoDerivation` directly! Couple of reasons:

1. `cargoBuild` is really just a thin layer over `mkCargoDerivation`. [All it does is set `pnameSuffix` and `buildPhaseCargoCommand`]
2. `mkCargoDerivation` allows setting `pname` suffix directly :smile:

**Comment by dpc** [comment]
Wouldn't it be nice to allow users to overwrite the default suffix though? Shorter (for the user), easier to understand, etc

**Comment by ipetkov** [comment]
Sure, that's exactly what `mkCargoDerivation` is for! It's publicly documented so users don't have to be "afraid" of using it :smile: 

(IMO it's a clearer distinction to tell users "use `mkCargoDerivation` if you want to customize things" than make every possible thing configurable at every level of the API, esp when you have to start trying to turn other things off that another helper is introducing)

**Comment by akorchyn** [comment]
I have another trouble with pnameSuffix. It fails to run in the workspace. If you have a workspace, it will do something like this:
`cargo clippy --profile release --package package-name-clippy` and it will fail the build.
