### ISSUE TITLE
I keep getting my things recompiled (when using with lorri)

### ISSUE THREAD

**Issue by dpc** [ipetkov/crane#25]
I'm trying `crane` out, to move from `naersk`. I've already created #24 , but I've noticed one issue that I'd like to report separately.

Whenever I switch between `nix run .#`, and getting `devShell` from `lorri`, I see that all the deps are getting recompiled. Can this be helped? Is it something about my `flake.nix` that invalidates the cache? Or is it just how `crane` works and it's meant to be used on in a CI, where no one will be getting dev shells?

**Comment by ipetkov** [comment]
> Is it something about my flake.nix that invalidates the cache?

I'm not exactly sure why, but I think that is the case. Looking at this bit of the configuration looks off to me:

```nix
cargoArtifacts = craneLib.buildDepsOnly {
  inherit src;
  buildInputs = [
    pkgs.pango
      pkgs.atk
      pkgs.gtk3
  ];
  nativeBuildInputs = [
    pkgs.pkgconfig
      fenix-channel.rustc
  ];
};

mycitadel = craneLib.buildPackage {
  inherit cargoArtifacts src;
  nativeBuildInputs = cargoArtifacts.nativeBuildInputs;
  buildInputs = cargoArtifacts.buildInputs;

  pname = "mycitadel";
};
```

In this case, `cargoArtifacts` is a derivation and not the raw attr set passed into `buildDepsOnly`, thus `cargoArtifacts.{buildInputs,nativeBuildInputs}` is likely pointing to something else which causes the invalidation.

Changing the config to the following does not recompile the dependencies, even after I made a change to the source files:

```nix
mycitadel = craneLib.buildPackage {
  src = ./.;
  pname = "mycitadel";
  buildInputs = [
    pkgs.pango
      pkgs.atk
      pkgs.gtk3
  ];
  nativeBuildInputs = [
    pkgs.pkgconfig
      fenix-channel.rustc
  ];
};
```

**Comment by dpc** [comment]
Thanks for responding!

I was under impression that I was supposed to split the build into two different steps - one for deps, one for the build, and possibly more if so I desired to get caching and other interesting behavior (like checks before build). I think I was mostly following https://github.com/ipetkov/crane#example-one as a most general reference. So - if I wanted multi-step build where things are split, do I do something differently (I only understand enough Nix to copy&paste&modify-until-works), or is that cache-invalidation something not expected?

**Comment by ipetkov** [comment]
The two step build process is done automatically when you use the "short-hand" format of not specifying `cargoArtifacts`. You can think of:

```nix
craneLib.buildPackage {
  foo = "fooArg";
  bar = "barArg";
}
```

As if you wrote the following by hand:

```nix
let
   args = {
     foo = "fooArg";
     bar = "barArg";
   };
   firstStage = craneLib.buildDepsOnly args;
   secondStageArgs = args // { cargoArtifacts = firstStage; };
in
craneLib.buildPackage secondStageArgs;
```

The first example in the README tries to be a bit more explicit in showing that you have the flexibility to order and compose steps as you'd like (e.g. if you wanted to build dependencies first, compile the crate second, and then run tests with code coverage, and so on).

The cache invalidation you ran into is not expected (or desirable!). Assuming things are configured correctly, cargo should not have to recompile the crates which were already compiled in the previous step. If that happens, there may be a bug (like either artifacts are getting lost, or the compiler version changed so they could not be reused, etc.). Happy to comment more on a specific configuration if it's causing headaches, but I'd recommend starting out with the short hand format to get things working and see if that resolves the cache invalidation issues.

The [quick-start](https://github.com/ipetkov/crane/blob/a3a6df218107f929a3f338bb34a5c5bc550a5579/examples/quick-start/flake.nix) also has an example of a more complicated setup that you can use as a starting point (just delete any of the things you don't need!). Feel free to ask for help if you get stuck too

**Comment by dpc** [comment]
> The two step build process is done automatically when you use the "short-hand" 

I understand that, but I also though that my unnecessary-longer 2 step version was supposed to work the same way.

> If that happens, there may be a bug

Yeah, that's kind of what I was thinking when reporting it. I still don't know if I did something wrong in my 2 step version, or is it a bug. I also can't help, since my nix-fu is too weak.

I will use the shorter version for now and that does it for me (thank you for help!). Feel free to close this if you think there's no issue or leave open if you think it's something that should be investigated/fixed.

**Comment by ipetkov** [comment]
Just to be clear, if you wanted to use the longer-form you can do so (as long as you don't use `cargoArtifacts.WHATEVER` directly). Changing to the following version of your flake still builds without invalidating anything

```nix
let
      commonArgs = {
        src = ./.;
        buildInputs = [
          pkgs.pango
          pkgs.atk
          pkgs.gtk3
        ];
        nativeBuildInputs = [
          pkgs.pkgconfig
          fenix-channel.rustc
        ];
      };

      cargoArtifacts = craneLib.buildDepsOnly (commonArgs // {
        # Overrides for this derivation only
        pname = "mycitadel-deps";
      });

      mycitadel = craneLib.buildPackage (commonArgs // {
        # Overrides for this derivation only
        pname = "mycitadel";
      });
in
{} # rest of flake
```

**Comment by ipetkov** [comment]
Just updated the README example to hopefully be less confusing to the next person. Thanks again for your feedback @dpc, feel free to open another issue if you hit any other problems (including apparent cache invalidation)!
