### ISSUE TITLE
Copy build file outputs to output dir

### ISSUE THREAD

**Issue by benwis** [ipetkov/crane#251]
This is another of my basic questions, but I'm using crane to build a workspace. This is what I tried.
```nix
  vidette = craneLib.buildPackage (commonArgs // {
            inherit cargoArtifacts;
            pname = "vidette";
            buildPhaseCargoCommand = "cargo leptos build --release";
            installPhaseCommand = ''
            cp $self/target/release/vidette_server $out/bin/
            cp -r $self/target/site $out/bin/
            '';
            # Prevent cargo test and nextest from duplicating tests
            doCheck = false;
            # ALL CAPITAL derivations will get forwarded to mkDerivation and will set the env var during build
            SQLX_OFFLINE = "true";
            APP_ENVIRONMENT = "production";
          });
```
If i omit installPhaseCommand it complains that it can't find the JSON file output of the buildPhaseCargoCommand, so I tried that, but I don't really know where it's building the outputs to.

Basically I need to do two things(I think)
1. Copy target/server/release/vidette_server to the output/bin folder
2. Copy the target/site folder to the same dir, so probably output/bin.
Any tips?

**Comment by dpc** [comment]
It complains that it can't find json, because by overwriting `buildPhaseCargoCommand` you are overwriting the default https://github.com/ipetkov/crane/blob/953b70da2813fb882c39890f2514e7db76fc8843/lib/buildPackage.nix#L41 which has an argument to produce the file. You probably want to only overwrite `cargoBuildCommand`

**Comment by ipetkov** [comment]
Hi @benwis, adding on to what @dpc said, you might want also to [use a _post-install hook_](https://nixos.org/manual/nixpkgs/unstable/#ssec-install-phase) to run whatever additional code you need but without overwriting the default install behavior!

```nix
vidette = craneLib.buildPackage (commonArgs // {
            inherit cargoArtifacts;
            pname = "vidette";
            cargoBuildCommand = "cargo leptos build --release";
            postInstall = ''
            cp $self/target/release/vidette_server $out/bin/
            cp -r $self/target/site $out/bin/
            '';
            # Prevent cargo test and nextest from duplicating tests
            doCheck = false;
            # ALL CAPITAL derivations will get forwarded to mkDerivation and will set the env var during build
            SQLX_OFFLINE = "true";
            APP_ENVIRONMENT = "production";
          });
```

**Comment by dpc** [comment]
BTW. all `crane` commands are almost always 1:1 stored under `lib` and most of them are relatively short and simple, so I've learned to just read their source whenever I'm confused about anything.
