### ISSUE TITLE
Examples' devShells don't actually inherit inptus from checks

### ISSUE THREAD

**Issue by mrkkrp** [ipetkov/crane#253]
I've more or less followed the example from the docs, in that I have defined `commonArgs`, etc. However, I'm a bit puzzled now that when I have

```nix
          devShells.default = pkgs.mkShell {
            inputsFrom = builtins.attrValues self.checks;

            buildInputs = [
              pkgs.libraw_unstable.dev # system library
            ];

            nativeBuildInputs = with pkgs; [
              cargo
              clippy
              rust-analyzer
              rustc
              rustfmt

              pkgs.pkg-config # pkg config
            ];
```

I can observe that `PKG_CONFIG_PATH` is correctly set in the development shell. Also, running `cargo build` succeeds without issues from the development shell. However if I add the same build inputs to `commonArgs`:

```nix
          commonArgs = {
            inherit src;
            buildInputs = [
              pkgs.libraw_unstable.dev
            ];
            nativeBuildInputs = [
              pkgs.pkg-config
            ];
          };
```

Not only this does not set `PKG_CONFIG_PATH` in the development shell (something I would have expected from          `inputsFrom = builtins.attrValues self.checks`), but also `nix build` fails like so:

```
error: builder for '/nix/store/2qxz3yn0kbban05dn89avpi2cgnqhcrf-raw-glue-deps-0.1.0.drv' failed with exit code 101;
       last 10 log lines:
       >   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
       >   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
       >   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
       >   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
       >   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
       >
       >   --- stderr
       >   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', /nix/store/np0wdl6v4dy8xcaiwiqx7rqssv6k1v15-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/libraw-sys-0.1.1/build.rs:221:40
       >   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
       > warning: build failed, waiting for other jobs to finish...
       For full logs, run 'nix log /nix/store/2qxz3yn0kbban05dn89avpi2cgnqhcrf-raw-glue-deps-0.1.0.drv'.
```

`buildInputs` and `nativeBuildInputs` not being propagated through `inputsFrom` is a nuisance, but `nix build` not working is a real problem. I was wondering if I'm missing something here, why `cargo build` from the development shell works while `nix build` fails with some kind of permission denied error?

If it is of any help, I've my setup here: https://github.com/mrkkrp/raw-glue/pull/1

**Comment by dpc** [comment]
Possibly the same issue as https://github.com/ipetkov/crane/issues/249#issuecomment-1441344606

**Comment by ipetkov** [comment]
Unfortunately this is an upstream issue with the `libraw-sys` crate's build script, [assuming that the current directory is writable](https://github.com/dcuddeback/libraw-sys/blob/b042355e3541df27f40905b871a3f7bd1e81a405/build.rs#L221). Cargo's documentation [states that build scripts should be using the $OUT_DIR variable and not attempt to modify any files outside of there](https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script).

My advice is to either send a PR to that crate to update the build script, or make your own fork with the corrections.

There is also [this nuclear option](https://crane.dev/faq/sandbox-unfriendly-build-scripts.html) for making the vendored source directory writable, but it is very wasteful when running builds and at best a bandaid to the underlying issue

**Comment by mrkkrp** [comment]
Thanks for your response :+1:

Regarding the first part of my question, is there a way to reduce the duplication regarding

```nix
          commonArgs = {
            inherit src;
            buildInputs = [
              pkgs.libraw_unstable.dev
            ];
            nativeBuildInputs = [
              pkgs.pkg-config
            ];
          };
```

? It appears that `commonArgs` is the right place to add `buildInputs` and `nativeBuildInputs`, but is there a way to make dev shell take these into account as well?

```nix
inputsFrom = builtins.attrValues self.checks;
```

Somehow this is not working. Perhaps I should add a new dictionary with `buildInputs` and `nativeBuildInputs` and then merge it into `commonArgs` as well as into `pkgs.mkShell`?

**Comment by ipetkov** [comment]
> Somehow this is not working. Perhaps I should add a new dictionary with `buildInputs` and `nativeBuildInputs` and then merge it into `commonArgs` as well as into `pkgs.mkShell`?

Yep this is a totally valid way to go around it, especially if `inputsFrom` isn't quite doing the right thing. I'd also recommend using `lib.recursiveUpdate` where needed for deep merges

```nix
let
  commonBuildAndShellArgs = {
    buildInputs = [ /* etc */ ];
    nativeBuildInputs = [ /* etc */ ];
  };

  commonArgs = pkgs.lib.recursiveUpdate commonBuildAndShellArgs {
    inherit src;
  };

  /* etc */
in {
  devShells.default = pkgs.mkShell (pkgs.lib.recursiveUpdate commonBuildAndShellArgs {
    buildInputs = [ /* extra inputs needed only by the shell */ ];
  });
}
```

**Comment by mrkkrp** [comment]
Thanks!

**Comment by ipetkov** [comment]
Turns out this didn't work because the examples are wrong :sweat_smile: 

It should be `inputsFrom = builtins.attrValues self.checks.${system};` since `self` refers to the entire flake itself and not one scoped to the current system! I'll have this fixed in a second, thanks for reporting it!
