### ISSUE TITLE
Add `path` helper which delegates to `builtins.path` and update examples and docs

### ISSUE THREAD

**Issue by ipetkov** [ipetkov/crane#272]
### Discussed in https://github.com/ipetkov/crane/discussions/269

<div type='discussions-op-text'>

<sup>Originally posted by **dpc** March 15, 2023</sup>
One of our contributors pointed out that they didn't get cached artifacts from cachix as they were using a different project name than what's the default, and pointed out to:

https://nix.dev/anti-patterns/language#reproducibility-referencing-top-level-directory-with

I'm going change our extra-filtering functions, but I wonder if crane should use it e.g. in the examples (https://crane.dev/examples/quick-start.html). I also wonder - if my code uses `src = ./.;` could crane "wrap it" with `builtins.path` internally? Does it already? Should it?</div>

---
While we're at it, maybe we should add a `craneLib.path`helper which takes a path and calls `builtins.path`, setting name to the workspace name (or `"source"` if no name is set). This would make it slightly less verbose than filling out `builtins.path` directly

**Comment by dpc** [comment]
`craneLib.path` works for me.
