### ISSUE TITLE
vendorCargoDeps does not accept direct Cargo.lock file

### ISSUE THREAD

**Issue by Infinidoge** [ipetkov/crane#275]
Within `vendorCargoDeps`, there is an error thrown by a lack of filling in the `src` argument, stating:
```
unable to find `src` attribute. consider one of the following:
- set `cargoVendorDir = vendorCargoDeps { cargoLock = ./some/path/to/Cargo.lock; }`
- set `cargoVendorDir = vendorCargoDeps { src = ./src/containing/cargo/lock/file; }`
- set `cargoVendorDir = null` to skip vendoring altogether
```

Based on this, one would expect that `vendorCargoDeps { cargoLock = ./some/path/to/Cargo.lock; }` would work, however it does not.
The part of `vendorCargoDeps` that throws the error occurs before the `cargoLock` argument is ever checked, so the error gets thrown regardless of the presence of `cargoLock`.

Relevant lines: https://github.com/ipetkov/crane/blob/2552a2d1ccf33d43259a9e00f93dbacb9e6d6bed/lib/vendorCargoDeps.nix#L19-L27

**Comment by ipetkov** [comment]
Ah thanks for reporting this @Infinidoge! `vendorCargoDeps` _does_ accept a `cargoLock`, but the checks for any `.cargo/config.toml` files is unconditionally assuming `args.src` has been set. I'll have a fix for this in a moment

**Comment by Infinidoge** [comment]
If the `src` isn't provided, it currently `throw`s, which is the main problem at hand.

**Comment by ipetkov** [comment]
> If the `src` isn't provided, it currently `throw`s, which is the main problem at hand.

Nix is lazily evaluated, as long as nothing depends on evaluating the local variable `src` it won't throw! I've added some test cases which validate all possible (minimal) inputs so we won't have any future regressions there

**Comment by Infinidoge** [comment]
Oh right, fair point, sometimes I don't think lazily enough.

**Comment by kuviman** [comment]
I am getting this error on current master, issue should be reopened?

**Comment by ipetkov** [comment]
@kuviman please open a new issue with a flake which can reproduce the problem!
