### ISSUE TITLE
"unable to find Cargo.lock" when cross compiling

### ISSUE THREAD

**Issue by Witcher01** [ipetkov/crane#279]
I'm trying to cross compile a Rust project for the ESP32-C3 with Nix and crane but get the following error when trying to compile:

```
error: unable to find Cargo.lock at /nix/store/i3mgdz87yb2ln7vdg10xrql7np3816v1-kgcf9rhid8vnhzji5y3893i2n2jbzmyw-source. please ensure one of the following:
       - a Cargo.lock exists at the root of the source directory of the derivation
       - set `cargoVendorDir = vendorCargoDeps { cargoLock = ./some/path/to/Cargo.lock; }`
       - set `cargoVendorDir = vendorCargoDeps { src = ./src/containing/cargo/lock/file; }`
       - set `cargoVendorDir = null` to skip vendoring altogether
(use '--show-trace' to show detailed location information)
```

My flake.nix looks like this:

```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    crane = {
      url = "github:ipetkov/crane";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    flake-utils.url = "github:numtide/flake-utils";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs = {
        nixpkgs.follows = "nixpkgs";
        flake-utils.follows = "flake-utils";
      };
    };
  };

  outputs = { self, nixpkgs, crane, flake-utils, rust-overlay }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs {
          system = system;
          overlays = [ (import rust-overlay) ];
        };

        rustToolchain = pkgs.pkgsBuildHost.rust-bin.fromRustupToolchainFile
          ./rust-toolchain.toml;
        lib = crane.lib.${system}.overrideToolchain rustToolchain;

        esp-rs-nix-test = lib.buildPackage {
          src = ./.;
          #nativeBuildInputs = with pkgs; [];
          installCargoArtifactsMode = "use-symlink";
        };

      in { packages.default = esp-rs-nix-test; });
}
```

rust-toolchain.toml:

```toml
[toolchain]
channel = "nightly-2023-02-01"
```

.cargo/config.toml

```toml
[build]
target = "riscv32imc-esp-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash --monitor"

[target.xtensa-esp32s2-espidf]
linker = "ldproxy"
runner = "espflash --monitor"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "espflash --monitor"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash --monitor"
rustflags = ["-C", "default-linker-libraries"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
ESP_IDF_VERSION = "release/v4.4"
```

This is tried with the minimal example that I got by using the [esp-idf-template](https://github.com/esp-rs/esp-idf-template/).

Originally, I got another error for a private project and stumbled upon this one when trying to get the minimal example.
If it helps narrow it down: The original project, using all the same settings and flake.nix, gave me this error:

```
error: builder for '/nix/store/0nzi1i912i29hn95ibj8dhs4hlh8m2fw-private-project-deps-0.1.0.drv' failed with exit code 101;
       last 10 log lines:
       > Executing configureCargoCommonVars
       > configuring
       > will append /build/source/.cargo-home/config.toml with contents of /nix/store/9b9k0dv7lswd736mbd4zx8s9ff9nwvzx-vendor-cargo-deps/config.toml
       > default configurePhase, nothing to do
       > building
       > ++ command cargo --version
       > cargo 1.69.0-nightly (3c5af6bed 2023-01-24)
       > ++ command cargo check --release --all-targets
       > error: "/nix/store/8rnlzjxzjm0dq4z581pnxdwh8j9lw7cd-rust-default-1.69.0-nightly-2023-02-01/lib/rustlib/src/rust/Cargo.lock" does not exist, unable to build with the standard library, try:
       >         rustup component add rust-src
       For full logs, run 'nix log /nix/store/0nzi1i912i29hn95ibj8dhs4hlh8m2fw-private-project-deps-0.1.0.drv'.
error: 1 dependencies of derivation '/nix/store/pnpvwkfgvqvnc9ps1p3dl43rhwlb5jh3-private-project-0.1.0.drv' failed to build
```

**Comment by dpc** [comment]
You're missing `rust-src` component. The missing path is `"/nix/store/8rnlzjxzjm0dq4z581pnxdwh8j9lw7cd-rust-default-1.69.0-nightly-2023-02-01/lib/rustlib/src/rust/Cargo.lock"`

**Comment by dpc** [comment]
Example from our project: https://github.com/fedimint/fedimint/blob/d90fb1d4bc55b2f567e3bea62eb8dd4b30137ebf/flake.nix#L165

**Comment by dpc** [comment]
It's probably the whole cross-compilation target that is missing? I'm not familiar with `pkgs.pkgsBuildHost.rust-bin.fromRustupToolchainFile`. Maybe crane cleans up the `rust-toolchain.toml` when it's building deps as well - something to look out for.

Crane can be a bit tricky, and cross-compilation is often a headache.

BTW. @ipetkov - just crossed my mind. If there was an easy way t disable file filtering when building deps (or anywhere else), it would be easy for the users to rule out problems with file filtering.

**Comment by ipetkov** [comment]
@Witcher01 your original post mentions two issues so let's take a look at them separately:

---
The first mentioned error was:
> error: unable to find Cargo.lock at /nix/store/i3mgdz87yb2ln7vdg10xrql7np3816v1-kgcf9rhid8vnhzji5y3893i2n2jbzmyw-source

`crane` needs to find the project's `Cargo.lock` file at _evaluation time_ to figure out which crates to pull in. This error can happen for a number of reasons:

* if you are using flakes and have not committed (or staged) the `Cargo.lock` file, then as far as Nix is concerned the file does not exist. Make sure to `git add -N Cargo.lock` and try again
* Another issue could be if `Cargo.lock` is in a subdirectory relative to the path provided in `src`. In your example config it shows `src = ./.;`: is `Cargo.lock ` at the root of the project or is it in a nested directory?
   - If it is nested there are two approaches to take:
      1. change `src` to point to the directory which contains `Cargo.lock`, e.g. `src = ./mycrate;`
      2. alternatively, you can follow the suggestion in the error message and set `cargoLock` with a path to `Cargo.lock`, e.g. `cargoLock = ./mycrate/Cargo.lock;`
* if none of these apply, you can also take a look at `/nix/store/i3mgdz87yb2ln7vdg10xrql7np3816v1-kgcf9rhid8vnhzji5y3893i2n2jbzmyw-source` which is the (cleaned) version of your project source as it was copied to the Nix store. If `Cargo.lock` is missing from there completely there might be another issue with Nix seeing the file

---
The second error you mentioned was:

> error: "/nix/store/8rnlzjxzjm0dq4z581pnxdwh8j9lw7cd-rust-default-1.69.0-nightly-2023-02-01/lib/rustlib/src/rust/Cargo.lock" does not exist, unable to build with the standard library

This has to do with cross compilation. There are various targets for which the Rust toolchain will automatically distribute pre-built binaries of the standard library (e.g. Linux, Windows, macOS, etc.), but for other targets (e.g. embedded) each project needs to compile their own version of the stdlib from source.

In this case, Nix needs to see the Rust stdlib source, but it won't see that unless the `rust-src` component is added (via `extensions = [ "rust-src" ];`) like @dpc suggested.

> I'm just very confused because building natively works perfectly fine without defining components = [ "rust-src" ] or anything else with the same flake. Can you explain why this is?

One reason why the build might work _outside_ of Nix is if you are using rustup and happen to have the `rust-src` component already added (keep in mind that when building inside of the Nix sandbox, the builder cannot see things like external rustup installations, you'll need to ensure the component is added to the specified toolchain).

---
> If there was an easy way t disable file filtering when building deps (or anywhere else), it would be easy for the users to rule out problems with file filtering.

@dpc I suppose one option is to set `cargoArtifacts = null;` and try building that way. Everything will be built from scratch, but if that succeeds then there is something missing with the dummification process.

**Comment by ipetkov** [comment]
> Regarding the second issue: As mentioned before, I added the line `components = [ "rust-src" ]` (assuming you meant `components` and not `extensions`, I can't find anything about the latter in the rustup book) to my `rust-toolchain.toml` which lets the build proceed.

rustup calls them "components" but `rust-overlay` (which your earlier example uses) [calls them `extensions`](https://github.com/oxalica/rust-overlay#cheat-sheet-common-usage-of-rust-bin), but since you are using `fromRustupToolchainFile` you can use the `rustup` syntax in that file!

> It seems like you missed the third error I posted, though, which is what I'm currently still struggling with

I wasn't sure if that was somehow related to the first problem, so I wanted to make suggestions one problem at a time 😄 

Looking at it a bit more closely I think this is a known limitation (I believe it was reported somewhere else, I'll try to find the link). Basically `crane` will vendor all the dependencies of your `Cargo.lock` file, as it doesn't know anything about the `Cargo.lock` from the `rust-src` component. When the std lib crates try to get compiled those crates end up missing from the vendor directory and the error comes up

The general solution for this would require #260 and vendoring the crates from both `Cargo.lock`s

**Comment by ipetkov** [comment]
I've opened https://github.com/ipetkov/crane/pull/287 which should address this! It adds `vendorMultipleCargoDeps` which allows specifying any number of `Cargo.lock` files (or their read/parsed equivalents), including the `Cargo.lock` file associated with the toolchain. Check out the added example for how to get things working!
