### ISSUE TITLE
How to handle dependencies?

### ISSUE THREAD

**Issue by lovesegfault** [ipetkov/crane#3]
If I have a crate which depends on some system library (i.e. I have a `buildInput`), how should I tell crane to include that dependency in the closure?

Likewise, if I depend on some tool at build time (i.e. I have a `nativeBuildInput`) to run a `build.rs` script, where do I specify that?

**Comment by ipetkov** [comment]
You can specify inputs or anything else in the same way you would with a `stdenv.mkDerivation` call, in fact, all parameters (except for crane specifics) are eventually passed down to `stdenv.mkDerivation`.

In fact, the alternative registry example happens to need some extra inputs and offers a good example of this: https://github.com/ipetkov/crane/blob/36c1236333f36dfe87c3694ac808de100e63b01f/examples/alt-registry/flake.nix#L49-L57

Does this help?

**Comment by lovesegfault** [comment]
Oh, neat, I think I had missed that in the main docs, probably should've looked at all the examples before opening an issue.

A follow-up: if I add `buildInputs` to my `cargoArtifacts = craneLib.buildDepsOnly ...` will they be propagated correctly to the `cargoClippy` and the final `buildPackage`?

**Comment by ipetkov** [comment]
Just updated the README in `5afc3e94fdf7731ccea2395947f1cd37aec5a2d5` to hint at this a bit more easily, but open to any other suggestions for improving the docs!

> A follow-up: if I add `buildInputs` to my `cargoArtifacts = craneLib.buildDepsOnly ...` will they be propagated correctly to the `cargoClippy` and the final `buildPackage`?

No, unfortunately if you explicitly set `cargoArtifacts = craneLib.buildDepsOnly { ... };` they will not automatically get propagated, you'd need to ensure the inputs are set to both.

If, however, you are only using `buildPackage` directly without setting `cargoArtifacts`, then `cargoArtifacts` will automatically get instantiated by passing `buildPackage`'s attrset to `buildDepsOnly`.

**Comment by lovesegfault** [comment]
> Just updated the README in https://github.com/ipetkov/crane/commit/5afc3e94fdf7731ccea2395947f1cd37aec5a2d5 to hint at this a bit more easily, but open to any other suggestions for improving the docs!

Awesome, I think that should clear it up :)

> No, unfortunately if you explicitly set cargoArtifacts = craneLib.buildDepsOnly { ... }; they will not automatically get propagated, you'd need to ensure the inputs are set to both.

Understood, thanks for the clarification!

Feel free to close this issue :)

**Comment by ipetkov** [comment]
No worries! I've also enabled the discussions tab, so feel free to open any other questions there (odds are, someone else is wondering the same thing and the docs could use some fresh eyes :smile: )
