### ISSUE TITLE
Support for overriding attrs / scope and common context.

### ISSUE THREAD

**Issue by dpc** [ipetkov/crane#300]
I'm using crane in more and more projects, and I'm getting annoyed at the boilerplate I have to produce. Some (most) of the projects I deal with are big and have lots of requirements (lots of derivations (selected-crates, whole workspaces, code coverage builds), support for dev/release/ci build profiles, cross-compilation to multiple targets and so and so), so any papercuts and boilerplate adds up. Crane is able to deliver on everything that I throw at it, so that's great, but I found myself investigating building my own "libraries" wrapping `crane` just to cut on some of the bloat.

While I was thinking and designing abstractions around, it occurred to me that `crane` should be able to help me (and other heavy users) for most of that stuff if it could do one extra thing, which seems well supported in many Nix things - supporting overridable context/defaults.

I usually have to resort to this pattern:

```
  workspaceBuild = craneLib.cargoBuild (commonArgs // {
    version = "0.0.1";
    cargoArtifacts = workspaceDeps;
    cargoExtraArgs = "--locked";
    doCheck = false;
  });
```

and it makes me think: why do I have to pass this `commonArgs` to every call? Couldn't I specify somewhere at point where I'm creating `craneLib` what I need and crane could remember it?

When I do:

```
craneLibNative = crane.lib.${system}.overrideToolchain toolchains.fenixToolchain;
```

I wish I could also specify:

* which `CARGO_PROFILE` to use/default to
* which `CARGO_BUILD_TARGET` to use/default to
* which `src` to default to (so I can do a simple pre-filtering in a monorepo, to only bother with relevant Rust-related directories)
* any `buildInputs`, `buildNativeInputs` and environment variables that should be common (because 99% of the time they are exactly the same for all derivations)

It reminds me of `pkgs.<pkg>.overrideAttrs` that I often use, so I think it should be relatively natural/easy to implement? I hope.

**Comment by ipetkov** [comment]
This should have probably been documented from the start (though I didn't at the time since it's a much more "advanced" technique) but you can totally override any function definition since the result of `mkLib` is a `pkgs.lib.makeScope`. The syntax is very similar to working with overlays:

```nix
let
  craneLib' = (crane.mkLib pkgs).overrideScope' (final: prev: {
    mkCargoDerivation = args: prev.mkCargoDerivation ({
     # Add whatever new defaults you want here, but still lets the caller override them
      CARGO_PROFILE = "bench"; # E.g. always build in benchmark mode
    } // args);
  });
in
craneLib'.buildPackage {
  src = whatever;
}
```

(If you _really_ want to go crazy and replace any of `crane`'s internals, _technically_ you can, but I'm not providing any stability guarantees for which function accepts what stuff from pkgs and whatnot, but if you want to override defaults this way feel free!)

**Comment by dpc** [comment]
Awesome. I did see `scope` stuff in the `default.nix` but my Nix-fu is too weak. This should probably be better documented, unless I missed something.

I'll try to refactor some of my code to use this approach and will report back.

**Comment by ipetkov** [comment]
Yep I'll add a documentation section around this

**Comment by dpc** [comment]
@ipetkov Documentation is great, but already one thing came to my mind - could we have a hook for `defaultSrc`? If I wanted to do `pre-filtering` of what `src` `crane` going to see ... I would have to override every single command that I'm going to use? Do I understand it correctly?

I think it would be neat if crane could use overrideable `defaultSrc` (if set) instead of requiring `src` or defaulting to some `./.`.

Why? I have a monorepo with bunch of things: web UI, mobile UIs, Javascript code ... and a bunch of Rust crates. The `Cargo.toml` is at the root (for reasons). There's really no reason for `crane` builds to ever consider anything but `Cargo.*` and 3 or 4 directories, among many others. I wish I could pre-filter the source once, via scope overrides, and be done with it.

**Comment by ipetkov** [comment]
My worry for adding a `defaultSrc` hook would be increasing the confusion around the API and configuration esp when things get mixed and matched...

But I do recognize that having to do the `overrideScope'` yourself to achieve that is fairly annoying. One of the benefits of requiring `src` everywhere is it gives nice(r) error messages if someone forgets to set it. I'll think about this...

**Comment by dpc** [comment]
@ipetkov I was thinking a bit about it in the background, and maybe the whole `commonArgs` pattern could be used.

So every `craneLib.mkDerivation args` would be under the hood a `craneLib.mkDerivation (mergeSmartly scope.commonArgs args)`. I'm not sure if `mergeSmartly` could be `builtins.mergeAttrs` or something a tiny bit more application-specific would be needed.

Normal users don't even have to know about it. It would be set to `{}` and job done. *However* if you at even https://crane.dev/examples/quick-start.html `commonArgs` is always used. Maybe... it should even just be the default way of doing thing? The examples would probably look prettier, and be easier to understand.

**Comment by dpc** [comment]
So the quick start example would be:

```
        craneLib = crane.lib.${system}.withCommonArgs {  // a little helper to avoid meh-scope-API
          src = craneLib.cleanCargoSource (craneLib.path ./.); // can I use `cranLib` here, or need decompose?

          buildInputs = [
            # Add additional build inputs here
          ] ++ lib.optionals pkgs.stdenv.isDarwin [
            # Additional darwin specific inputs can be set here
            pkgs.libiconv
          ];
        };

...

        my-crate = craneLib.buildPackage {
          inherit cargoArtifacts;
        };
```

Something like that. In my opinion this is much tidier than `(commonArgs //` all over the place.
