### ISSUE TITLE
Git Dependency not working

### ISSUE THREAD

**Issue by NyCodeGHG** [ipetkov/crane#308]
Hi, I'm trying to build a project using crane which has a dependency on another git repository, but the build fails.
I'm using the exact [quick-start-simple](https://crane.dev/examples/quick-start-simple.html) example beside the modified Cargo.toml shown below.

This is the error i get.
```
evaluating derivation 'git+file:///home/marie/projects/test#packages.x86_64-linux.default'fatal: not a git repository: '.'
evaluating derivation 'git+file:///home/marie/projects/test#packages.x86_64-linux.default'fatal: not a git repository: '.'
warning: could not update local clone of Git repository 'https://github.com/asciinema/avt.git'; continuing with the most recent version
evaluating derivation 'git+file:///home/marie/projects/test#packages.x86_64-linux.default'fatal: not a git repository: '.'
error: program 'git' failed with exit code 128
(use '--show-trace' to show detailed location information)
```

This is my Cargo.toml
```toml
[package]
name = "quick-start-simple"
version = "0.1.0"
edition = "2021"

[dependencies.agg]
git = "https://github.com/NyCodeGHG/agg"
rev = "2bebff3032b3319174809f301631e12c693e92b7"
version = "*"
```

I've noticed that the dependency has another git dependency, maybe that is the problem?

**Comment by ipetkov** [comment]
Hi @NyCodeGHG, is your `Cargo.lock` fully up to date? You can check this by running `cargo update; git add Cargo.lock`!

Cargo should recursively resolve all git dependencies of other git dependencies, but it usually requires invoking cargo directly (e.g. via `cargo update` or even `cargo build`, etc.) before the lock file is updated. Once all crates are included in the `Cargo.lock` they should get vendored appropriately!

Otherwise there might be an issue with the rest of the configuration? I was able to build the `quick-start-simple` example by updating `Cargo.toml` as shown above and then running `cargo update && nix flake check -L`

Hope this helps!

**Comment by NyCodeGHG** [comment]
My lockfile is up to date. The command only updated other dependencies, not the git one.
Also `cargo update && nix flake check -L` fails with the same error:
```
    Updating git repository `https://github.com/NyCodeGHG/agg`
    Updating crates.io index
    Updating git repository `https://github.com/asciinema/avt.git`
checking flake output 'checks'fatal: not a git repository: '.'
fatal: not a git repository: '.'
warning: could not update local clone of Git repository 'https://github.com/asciinema/avt.git'; continuing with the most recent version
checking flake output 'checks'fatal: not a git repository: '.'
error: program 'git' failed with exit code 128
(use '--show-trace' to show detailed location information)
```

**Comment by ipetkov** [comment]
Could you please share (an ideally minimal) version of your flake I can reproduce locally?

**Comment by NyCodeGHG** [comment]
This my minimal example which i tested locally: https://github.com/NyCodeGHG/crane-git-repo/

**Comment by ipetkov** [comment]
Running `nix flake check -L github:NyCodeGHG/crane-git-repo/` on my `x86_64-linux` machine works just fine. Similarly `nix build -L github:NyCodeGHG/crane-git-repo/` also succeeds.

Do you have the Nix sandbox enabled? Do you have a `.cargo/config.toml` file somewhere in your directory hierarchy which is doing source replacement with another git repo?

**Comment by NyCodeGHG** [comment]
Hmm, both commands fail on my machine.
I have the nix sandbox enabled and I also don't have a cargo config anywhere.

**Comment by ipetkov** [comment]
What version of Nix are you using btw?

I'd also try rebooting the system (effectively restarting the Nix daemon) and see if that helps

**Comment by NyCodeGHG** [comment]
I'm using nix 2.13.3
also rebooting did not help :(

**Comment by ipetkov** [comment]
> evaluating derivation 'git+file:///home/marie/projects/test#packages.x86_64-linux.default'fatal: not a git repository: '.'

I wonder if there is a broader issue with the overall flake that is being evaluated? Looking at the original error above hints something about this...

I would try commenting out everything in the flake until you get a clean evaluation, then start incrementally adding pieces back until you identify where the error is coming from

**Comment by NyCodeGHG** [comment]
I tried doing that but that didn't really work. I essentially have to comment out everything and i end up with a flake with no outputs.

**Comment by dpc** [comment]
I can't find `2bebff3032b3319174809f301631e12c693e92b7` in https://github.com/NyCodeGHG/agg (at least through the web UI)

**Comment by NyCodeGHG** [comment]
It's [here](https://github.com/NyCodeGHG/agg/commit/2bebff3032b3319174809f301631e12c693e92b7). The `generic-api` branch points to it.

**Comment by NyCodeGHG** [comment]
Okay I set up a vm running my exact system configuration (besides hardware) and it successfully builds. Seems like there is something very wrong with my laptop.

**Comment by ipetkov** [comment]
> But I think that picking up the git configuration is not intended, right?

This sounds like an issue with Nix itself (or rather how `nix` will authenticate when pulling a non-public git repo) since there isn't much we can control here. `crane` itself can't look at your git config either since `nix` will sandbox the evaluation...

I'm glad you were able to figure out the issue! I'm going to close for now but feel free to reopen if you have other questions!
