### ISSUE TITLE
Duplicate `crane-dummy` after upgrading crane to v0.12.1

### ISSUE THREAD

**Issue by dpc** [ipetkov/crane#312]
```
fedimint-workspace-deps> error: document output filename collision                                                                    
fedimint-workspace-deps> The bin `crane-dummy` in package `fedi-fedimintd v0.1.0 (/build/source/fedimintd)` has the same name as the bin `crane-dummy` in package `fedi-fedimint-cli v0.1.0 (/build/source/fedimint-cli)`.         
```

**Comment by dpc** [comment]
Seems to be working fine on v0.11.3.

**Comment by ipetkov** [comment]
Hmm I wonder if this is due to the `bindeps` changes that were made recently... Needs more investigation

**Comment by dpc** [comment]
This fixes it:

```
diff --git a/nix/craneBuild.nix b/nix/craneBuild.nix
index 37b085fdc2..0152a52510 100644
--- a/nix/craneBuild.nix
+++ b/nix/craneBuild.nix
@@ -6,7 +6,7 @@ craneLib.overrideScope' (self: prev: {
 
   workspaceDeps = self.buildDepsOnly (prev.commonArgsDepsOnly // {
     version = "0.0.1";
-    buildPhaseCargoCommand = "cargo doc --locked --profile $CARGO_PROFILE ; cargo check --locked --profile $CARGO_PROFILE --all-targets ; cargo build --locked --profile $CARGO_PROFILE --all-targets";
+    buildPhaseCargoCommand = "cargo check --locked --profile $CARGO_PROFILE --all-targets ; cargo build --locked --profile $CARGO_PROFILE --all-targets";
     doCheck = false;
   });
```

So it's seems it's only `cargo doc` that can't handle multiple crates named the same.

**Comment by dpc** [comment]
@ipetkov 

I've confirmed that:

```
diff --git a/lib/mkDummySrc.nix b/lib/mkDummySrc.nix
index 4d179a3..9b010f7 100644
--- a/lib/mkDummySrc.nix
+++ b/lib/mkDummySrc.nix
@@ -196,7 +196,7 @@ let
       '' + optionalString (trimmedCargoToml ? package) ''
         # To build regular and dev dependencies (cargo build + cargo test)
         ${cpDummy parentDir "src/lib.rs"}
-        ${cpDummy parentDir "src/bin/crane-dummy/main.rs"}
+        ${cpDummy parentDir "src/main.rs"}
 
         # Stub all other targets in case they have particular feature combinations
         ${safeStubLib}
```

fixes it for me. But I wonder if there was some deeper reason to use `bin/<x>/main.rs` (which will lead to binary always named `<x>` over `main.rs` (which I think will lead to binary named like the package). If there was, I guess using `bin/<x>-<package-name>/main.rs` would lead to a unique name.

**Comment by dpc** [comment]
@ipetkov Any thoughts? This blocks me from updating to newer `crane` versions.

**Comment by ipetkov** [comment]
@dpc short term you could set `extraDummyScript` to `rm -rf src/bin/crane-dummy/main.rs`

Long term we need to change the source dummification to ignore any extra targets (but allow opt-ing into dummifying them if necessary, e.g. for bindeps)

**Comment by dpc** [comment]
Worked.

For reference, I used:

```
        rm -f $(find $out | grep bin/crane-dummy/main.rs)
```

**Comment by simonzkl** [comment]
I'm not sure if this is related, but we've been also seeing this intermittently:

```
error: failed to remove file `/build/source/target/release/crane-dummy`
```

I have no idea how to reproduce it though, and it works fine if you attempt another build right after the failed one, which makes it very difficult to inspect and raises questions around reproducibility.

**Comment by javbit** [comment]
> ```
> error: failed to remove file `/build/source/target/release/crane-dummy`
> ```

I've also seen this issue.  I think it happens when there are jobs happening in parallel.  I'm going to test with `--max-jobs 1` to test my hypothesis.

> [It's] very difficult to inspect and raises questions around reproducibility.

My Nix experience very much has been filled with non-determinism and weird bugs :smiling_face_with_tear:.
