### ISSUE TITLE
Rebuilds on unrelated file changes

### ISSUE THREAD

**Issue by dpc** [ipetkov/crane#313]
Note: I'm on v0.11.3 due to #312 .

Yes. Me again, and we've been there before. :) So you know I use `crane` a lot, and have been debugging issues like this with your in the past, so 95% it's something non-trivial. :D

I have a derivation that goes "deps-only -> workspace -> test". Very usual for my projects. If I change a file (shell script running test) I get "deps-only" being rebuilt. Which is weird because  `mkDummySrc` would throw away that file anyway.

When I take the path with the source:

```
fedimint-workspace-deps> unpacking source archive /nix/store/kjgc2klpgkyklb0r6cxhig9v89v8ys95-source               
```

and run `tree <path1> > a` and `tree <path2> > b` on two builds where I changed that irrelevant file I get:

```
> diff -u a b
--- a   2023-05-02 13:57:44.094625961 -0700
+++ b   2023-05-02 13:58:16.704741386 -0700
@@ -1,4 +1,4 @@
-[4.0K]  /nix/store/zaj9dmjpfa9237l0bm9j81x5g0hcynx8-source
+[4.0K]  /nix/store/kjgc2klpgkyklb0r6cxhig9v89v8ys95-source
 ├── [4.0K]  bridge
 │   ├── [4.0K]  fedi-ffi
 │   │   ├── [2.2K]  Cargo.toml
```

That's it. As you can see other than the path, nothing in there changed, so why is the path different?

I verified with a recursive checksum that literally no byte is different:

```
> ./rblake2sum /nix/store/zaj9dmjpfa9237l0bm9j81x5g0hcynx8-source
5cc0cb4f5c52afa12d84daa7be2c774e503dcbe742c96d7c82bb2a7b2ec63785056aa98ba25dee6aba993524309f38504b97262ffc11af1433a694b0de689492 /nix/store/zaj9dmjpfa9237l0bm9j81x5g0hcynx8-source
> ./rblake2sum /nix/store/kjgc2klpgkyklb0r6cxhig9v89v8ys95-source
5cc0cb4f5c52afa12d84daa7be2c774e503dcbe742c96d7c82bb2a7b2ec63785056aa98ba25dee6aba993524309f38504b97262ffc11af1433a694b0de689492 /nix/store/kjgc2klpgkyklb0r6cxhig9v89v8ys95-source
```

Any hints what else could I do to debug it?

**Comment by ipetkov** [comment]
Here's how I've tried to debug issues like this in the past:

1. Grab a recursive dump of what your derivation depends on via `nix show-derivation -r .#mypkg`
2. Make the seemingly unrelated change which would trigger a rebuild
3. Grab a new dump via `nix show-derivation -r .#mypkg`
4. Diff the two outputs

You can obviously ignore everything which is the same in the diff. Find the lowest dependency derivation (in this case likely a source related to dummification or something similar) and compare what actually is different.

Sometimes it's possible for two different derivations to have the exact same output, but if they capture two different inputs/variables/whatever, they will end up having different hashes...

**Comment by dpc** [comment]
Thank you. BTW. I still don't really understand at which point post-filtering caching is achieved.

If I start from a directory with 100 files, then filter it to directory with 1 file, at which point *exactly* does Nix decide to ignore the initial 100 files (among other things), and use only the one with 1 file as the "memoization key"?

**Comment by ipetkov** [comment]
When a source is coerced into a string Nix will apply the filter and put those contents in a fresh `/nix/store/...` entry and at this point anything which depends on that result will be rebuilt if this path changes (and it would only change if any of the files that the filter has accepted change themselves).

One possible question is: is the filter allowing too much? You can use [`lib.sources.trace`](https://noogle.dev/?selected=%22lib.sources.trace%22&term=%22sources%22) to debug what the filter is accepting or not

Another thing to explore is: is the unfiltered source somehow being captured or turned into a string and used in a derivation later? Nix has the concept of a "context" which means strings implicitly can carry their dependency around (e.g. if you did `x = "blah-${somedrv}";` then later `y = "yay-${x}";` and pass `y` to a derivation, that derivation will get rebuilt whenever `somedrv` changes).

The second one is tricker to catch, but that's where looking at the recursive derivation dependencies helps out

**Comment by dpc** [comment]
OK.

```
    dummySrc = craneLib.mkDummySrc {
      inherit src;

      extraDummyScript = ''
        cp -ar "${src}/.cargo" --no-target-directory $out/.cargo
      '';
    };
```

The `${src}` resolves to a full nix store path, which contaminates the whole derivation it seems?

But I'm looking at example in: https://github.com/ipetkov/crane/blob/master/docs/API.md#optional-attributes-14

and

```
      extraDummyScript = ''
        cp -ar ${./.cargo} --no-target-directory $out/.cargo
        cp -a ${./Cargo.wasm32.lock} $out/
      '';
```

is not working:

```
       error: getting status of '/nix/store/yk7k7kg4z8zk7qvirbvb8xfhqvsp468r-source/nix/.cargo': No such file or directory
```

Is it incorrect?

**Comment by dpc** [comment]
Thank you so much. As always.

**Comment by ipetkov** [comment]
Yeah Nix can be a bit opaque to debug unfortunately...

@dpc Would you be interested in contributing an improvement of the docs in this regard? You've got fresher eyes and an outside perspective debugging this which would be helpful in covering any documentation gaps 😄 

Doesn't have to be perfect so no pressure, happy to work with an outline too
