### ISSUE TITLE
File in parent folder no longer found

### ISSUE THREAD

**Issue by Anton-4** [ipetkov/crane#318]
Hi,
I'm [setting up crane for a complicated rust project](https://github.com/roc-lang/roc/blob/flake-build/flake.nix) where we also use zig. We have a `build.rs` file that calls zig through `std::process::Command`. In the parent folder of the dir with the `build.rs` file there is a `build.zig` file which the zig command can find without issues when using cargo.

With crane it fails to find the file:
```
nix build
warning: Git tree '/home/username/gitrepos/roc' is dirty
error: builder for '/nix/store/hnwpzrlviwz05z2yvjfs75iwwcl41xz7-roc-0.0.1.drv' failed with exit code 101;
       last 10 log lines:
       >
       >   --- stderr
       >   thread 'main' panicked at 'zig build ir -Drelease=true failed with:
       >
       >     info: Initialize a 'build.zig' template file with `zig init-lib` or `zig init-exe`,
       >   or see `zig --help` for more options.
       >   error: No 'build.zig' file found, in the current directory or any parent directories.
       >
       >   ', crates/compiler/builtins/bitcode/bc/build.rs:124:21
       >   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
       For full logs, run 'nix log /nix/store/hnwpzrlviwz05z2yvjfs75iwwcl41xz7-roc-0.0.1.drv'.
```

Does crane build directories in isolation? Can you provide some pointers on how I could resolve this issue?

Thanks for working on crane :heart:

**Comment by dpc** [comment]
https://github.com/roc-lang/roc/blob/dae1b9c24158d1e43c8827c0eee056b84112b6df/flake.nix#L120 `cleanCargoSource` will probably filter out zig files.

**Comment by Anton-4** [comment]
Riiight, thanks, I'll try without that

**Comment by ipetkov** [comment]
Closing this for the time being since the solution is to use a custom source filter, but feel free to reopen if you have other questions!
