### ISSUE TITLE
The non-zstd (default) artifacts mode is causing deps rebuild

### ISSUE THREAD

**Issue by dpc** [ipetkov/crane#323]
I was trying #322 and noticed that in my build, at the end of `buildWorkspaceDepsOnly` step, nix is doing bunch of `shrinking ...` and afterwards the `buildWorkspace` is rebuilding all the dependencies from scratch.

**Edit**: Just checked and it seems that `v0.12.1` behaves correctly. It also does the `shrinking` but when `buildWorkspace` starts it only builds local crates as expected.

BTW. It still seems to me that nix should not mess with these files under `./target`... seems sus, and takes extra time.

```
> cargo --version
cargo 1.67.0 (8ecd4f20a 2023-01-10)
> rustc --version
rustc 1.67.0 (fc594f156 2023-01-24)
```

**Comment by ipetkov** [comment]
> **Edit**: Just checked and it seems that `v0.12.1` behaves correctly. It also does the `shrinking` but when `buildWorkspace` starts it only builds local crates as expected.

@dpc just to be clear, are you only seeing this behavior on #322 but not in `v0.12.1`? If so we can move the convo there, otherwise we can investigate this further

**Comment by dpc** [comment]
I see it everywhere when I don't use `zstd`, and given that everything is fine with `v0.12.1`, it might not be actually any problem. (Though it looks weird and seems to waste time).

**Comment by ipetkov** [comment]
That might be from `mkDerivation`'s various post-installation hooks (which seek to strip out debug info and compress files, etc.) which might be crawling all the symlinked cargo artifacts. You could try [disabling those](https://nixos.org/manual/nixpkgs/unstable/#ssec-fixup-phase) and see if that helps!

**Comment by dpc** [comment]
I'm unable to reproduce. No idea what did I do wrong/different.
