### ISSUE TITLE
Use just build executable in check phase

### ISSUE THREAD

**Issue by RCasatta** [ipetkov/crane#331]
My test uses the binary executable, so I [tried](https://github.com/RCasatta/fbbe/pull/23/commits/0cdc3baad1f71c7b355a209bc14b5212024c96f2) to pass it via env var like so:

```
          bin = craneLib.buildPackage (commonArgs // {                          
            inherit cargoArtifacts BITCOIND_EXE;                                
            preCheckPhase = ''                                                  
              export FBBE_EXE=$out/bin/fbbe                                     
            '';                                                                 
          });
```

but it seems my test is not seeing the env var.

Doing some other tests I tried the [documentation](https://crane.dev/customizing_builds.html?highlight=phase#customizing-builds) code:

```
  postInstallPhase = ''
    echo "hello world" > $out/hello.txt
    # also install the README.md for good measure
    cp README.md $out/
  '';
```

but I can's see the hello.txt in my `/nix/store/..../` derivation output, is it executed?

(I am nix-noob, sorry if there is somethin obviously wrong in my tests)

**Comment by dpc** [comment]
:wave: A familiar face.

This seems like a more genric Nix issue. Ping me on https://matrix.to/#/#nix:nixos.org if you want more interactive help.

Are you using `nix flake -L build ...` to get logs messages? That's how I usually debug these things - add some `echo`, `find` and other debug info and run with `-L` to understand how things work.

**Comment by dpc** [comment]
@RCasatta 

ChatGPT says that `check` runs before `install` so you won't have `$out/bin/fbbe`. But after `build` so you should already have `./target/$CARGO_PROFILE/fbbe` I think.

But I'm not sure if you don't see the env set at all, or the binary isn't there.

**Comment by RCasatta** [comment]
👋🏼 ehehe how small is github??

it seems the env var is not seen at all because `assert!(std::env::var("FBBE_EXE").is_ok());` fails

I have to go now, I'll ping you tomorrow, thanks

**Comment by dpc** [comment]
> it seems the env var is not seen at all because assert!(std::env::var("FBBE_EXE").is_ok()); fails

That's weird. I doubt anything clears it there.

I'd try `-L` and maybe set `FBBE_EXE` in the main derivation to something to verify.

> 👋🏼 ehehe how small is github??

Hopefully big enough for both of us. :D

![](https://thumbs.gfycat.com/BlankFaintHammerkop-max-1mb.gif)

**Comment by ipetkov** [comment]
@RCasatta you might be looking for [`preCheck`](https://nixos.org/manual/nixpkgs/unstable/#ssec-check-phase) and not `preCheckPhase`

**Comment by RCasatta** [comment]
That fixed it thanks @ipetkov
