### ISSUE TITLE
Does crane break terminal settings / ANSI?

### ISSUE THREAD

**Issue by 0x241F31** [ipetkov/crane#337]
I wrapped [my project](https://github.com/MrFoxPro/lapce-nix) in crane and used Nushell script to run some `installPhaseCommand`s. I noticed that it outputs incorrectly. You can clone and run `nix build --print-build-logs` to see broken output
![image](https://github.com/ipetkov/crane/assets/17229619/f58b2a7c-2bb7-4049-bd85-6d40d4578df2)

I thought it could be Nix issue and fixed it by removing [filterANSIEscapes](https://github.com/NixOS/nix/blob/master/src/libutil/util.cc#L1504) from logger. 
But then I made two derivations: with `pkgs.nuenv.mkDerivation` and `pkgs.stdenv.mkDerivation`, both correctly produces output from Nushell scripts with original Nix:
![image](https://github.com/ipetkov/crane/assets/17229619/3be87a71-97b6-4c04-a25d-60536a20b14e)
You can try it: https://pastebin.com/i3wmRHZu

Any ideas?

**Comment by MrFoxPro** [comment]
Not related to this project
