### ISSUE TITLE
source is unconditionally filtered in patch phase 

### ISSUE THREAD

**Issue by jalil-salame** [ipetkov/crane#352]
Even when setting `src = ./.;` when applying a patch through `patches`, the sources are filtered (only `toml` and `rs` files are available).

This happened while I was trying to patch some C headers.

**Comment by dpc** [comment]
Is this happening in deps only build (which can sometimes be added implicitly)?

If so use explicit deps only build and `dummySrc`, `extraDummyScript` to control it, like this: https://github.com/fedimint/fedimint/blob/fff1aa0ffdaafa543df63f45890bfe3cd81cdd31/nix/craneCommon.nix#L143

But possibly your patch phase script is executed during implicit deps only build and solution is to just introduce an explicit one (without the patch phase script).

**Comment by jalil-salame** [comment]
> Is this happening in deps only build (which can sometimes be added implicitly)?

Yes!

> If so use explicit deps only build and `dummySrc`, `extraDummyScript` to control it, like this: https://github.com/fedimint/fedimint/blob/fff1aa0ffdaafa543df63f45890bfe3cd81cdd31/nix/craneCommon.nix#L143

I checked what I could do, and I think I'll need to patch the not deps only build, thanks!
