### ISSUE TITLE
How to influence wasm-bindgen-cli version

### ISSUE THREAD

**Issue by HBBrennan** [ipetkov/crane#354]
Hello, I have a rust project that is nearly identical to https://crane.dev/examples/trunk-workspace.html. When doing a nix build, I see get an error with a wasm-bindgen ABI version mismatch. Specifically:

```
configuring trunk tools
TRUNK_TOOLS_SASS=1.63.3 compiled with dart2js 3.0.4
TRUNK_TOOLS_WASM_BINDGEN=0.2.84
TRUNK_TOOLS_WASM_OPT=version_112
```
...
```
2023-07-06T22:43:26.680486Z  INFO using system installed binary app=wasm-bindgen version=0.2.84
2023-07-06T22:43:26.680589Z  INFO calling wasm-bindgen for client
error:

it looks like the Rust project used to create this wasm file was linked against
version of wasm-bindgen that uses a different bindgen format than this binary:

  rust wasm file schema version: 0.2.87
     this binary schema version: 0.2.84

Currently the bindgen format is unstable enough that these two schema versions
must exactly match. You can accomplish this by either updating the wasm-bindgen
dependency or this binary.
```

**Comment by ipetkov** [comment]
Hi @HBBrennan!

There's two ways that come to mind:
1. Update your `nixpkgs` input (or whatever instantiation of `pkgs` is passed into `crane.mkLib`) to use `wasm-bindgen` 0.2.87 (looks like the latest version of `wasm-bindgen-cli` is currently 0.2.84 in `nixpkgs-unstable`, you might need to apply your own patch/overlay or contribute the change upstream)
2. Downgrade your entire dependency tree to using `wasm-bindgen` 0.2.84 via `cargo update -p wasm-bindgen --precise 0.2.84` (and if that doesn't work, `cargo tree -i wasm-bindgen@0.2.87` may help you figure out what is pulling it in)

Hope this helps!

**Comment by HBBrennan** [comment]
Thank you so much I'll unblock myself with the latter. Love the project btw.

**Comment by jhartma** [comment]
Had the same problem and fixed it with ```wasm-bindgen = "= 0.2.84"```in Cargo.toml

**Comment by rambip** [comment]
Same problem here.
This really needs a fix !
If someone left `wasm-bindgen = "=0.2.84"` in her Cargo.toml, it will fail to build when the wasm-bindgen version change in nixpkgs.

I almost think it should be mandatory to set the wasm-bindgen vesrion in `buildTrunkPackage`, and let `crane` figure out where to fetch it.
You could try to download them from https://github.com/thedodd/trunk/releases, and if not present built it from source, with a pinned version.

I  already tried to do that in my projects (see [here](https://github.com/rambip/wasm-tooling/blob/main/wasm-bindgen.nix)), and I really think managing the wasm-bindgen version is a must for your library.

**Comment by lelgenio** [comment]
If you are using unstable (after https://github.com/NixOS/nixpkgs/pull/232070), you can also easily override `wasm-bindgen-cli`:
```nix
frontend = craneLib.buildTrunkPackage (defaultArgs // {
  nativeBuildInputs = [
    (wasm-bindgen-cli.override {
      version = "0.2.84";
      hash = "sha256-0rK+Yx4/Jy44Fw5VwJ3tG243ZsyOIBBehYU54XP/JGk=";
      cargoHash = "sha256-vcpxcRlW1OKoD64owFF6mkxSqmNrvY+y3Ckn5UwEQ50=";
    })
  ];
});
```

Maybe we should just backport part of that patch to 23.05, and document it?
No code for us to maintain, overriding should be easy for nix users to understand.

I agree with @rambip, the package should be passed via a required argument.
