### ISSUE TITLE
Build with `--locked` by default

### ISSUE THREAD

**Issue by ISibboI** [ipetkov/crane#372]
If the `Cargo.lock` is not up to date, crane will build all dependencies when executing `buildDepsOnly`, and then again when executing `buildPackage`. Building with `--locked` will cause it to throw an error instead.

Other than resulting in performance issues, the current behavior also makes the build impure, as it allows cargo to update the lock file as it pleases.

**Comment by dpc** [comment]
I already forgot all the details, but fwiw I've added `--locked` to craneLib invocation a while ago, because it seems just better.

**Comment by ipetkov** [comment]
Hi @ISibboI thanks for the suggestion, it's a good one! I'll have a PR up in a bit with the changes applied

> the current behavior also makes the build impure

I will note that whether or not the build is pure depends on whether the Nix sandbox is enabled. Assuming that it is, cargo won't be able to touch the network to pull in new crates (though caching can break if a package was dropped and that suddenly turns off feature flags in dependency crates, so it's worth while for the defaults to avoid)

**Comment by ISibboI** [comment]
Great thanks!
