### ISSUE TITLE
Consider including `clippy` and `rustfmt` in the `devshell` helper

### ISSUE THREAD

**Issue by ipetkov** [ipetkov/crane#383]
Just wanted to give some input as a fellow `crane` user: ensuring `clippy` and `rustfmt` are present (and overridable) can also prove itself to be helpful for a dev shell. (Not sure how easy that would be considering the `rust-analyzer` problem, or if this would be fully within the PR's scope; just wanted to throw the idea around.)

_Originally posted by @PgBiel in https://github.com/ipetkov/crane/issues/378#issuecomment-1704006774_

**Comment by 9999years** [comment]
This might warrant a more in-depth rethinking of the override system. Perhaps we could have separate functions for overriding the toolchain starting from a `nixpkgs` compiler vs a `oxalica/rust-overlay` compiler?

**Comment by ipetkov** [comment]
IMO it's fine if `craneLib.devshell` is a bit opinionated and lacks super fine grained overrides. Ultimately if someone wants really tight control over what their devshell includes they can drop down to `pkgs.mkShell`

I'd imagine most use cases would want to use all tools from the same toolchain (i.e. `craneLib.overrideToolchain` already does what is expected). What are the use cases for having fine grained control over pulling clippy from one toolchain but using rustfmt from another?

**Comment by PgBiel** [comment]
I'd add that at least a toggle for nightly `rustfmt` would probably be useful (since nightly rustfmt is required to use most formatting options). There's an `.override` option (`asNightly`) on the [rustfmt package from nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/rust/rustfmt.nix) which makes this very seamless.

**Comment by dpc** [comment]
> I'd add that at least a toggle for nightly `rustfmt` would probably be useful (since nightly rustfmt is required to use most formatting options).

FWI. In my project (personal and professional) we use stable toolchain with a nightly rustfmt, and I know other projects that do so as well.

**Comment by ipetkov** [comment]
Ah thanks for the feedback, I hadn't considered mixing a nightly rustfmt!

Though I suppose one would expect the same version of rustfmt would show up in the devshell? As in, I'd anticipate that once `crane.overrideToolchain` or `crane.overrideScope'` is used to set up the regular build, the devshell would use the same thing

Actually if any of the checks use `rustfmt` the devshell would end up inheriting it anyway through the `checks`/`inputsFrom` integration. Same with clippy :thinking:

**Comment by dpc** [comment]
Yes, using separate overrides for rustfmt in normal derivations vs nix shells seems like a footgun, if that's what you mean. Though in [Fedimint we derive bunch of toolchains, that contains all sorts of compenets](https://github.com/fedimint/fedimint/blob/d4ae51df9149dd5e7f3fef16f7e5f04c04ca117d/flake.toolchain.nix#L136) for different purposes: eg. lint CI in GH uses a different nix shell with only necessary elements, etc.


BTW, while at it. Recently [I wrapped `rustc` to extend it with a functionality to prevent it from building crates](https://github.com/fedimint/fedimint/pull/3062), to avoid cache breaking bugs that I was often introducing. I thought it's worth mentioning as a ... weird/crazy/cool things one can do with the toolchain.

**Comment by PgBiel** [comment]
> Ah thanks for the feedback, I hadn't considered mixing a nightly rustfmt!
> 
> Though I suppose one would expect the same version of rustfmt would show up in the devshell? As in, I'd anticipate that once `crane.overrideToolchain` or `crane.overrideScope'` is used to set up the regular build, the devshell would use the same thing
> 
> Actually if any of the checks use `rustfmt` the devshell would end up inheriting it anyway through the `checks`/`inputsFrom` integration. Same with clippy 🤔

Yeah, thinking further about it, I think the better solution might just be to inherit clippy and rustfmt from the toolchain / scope, and use `overrideScope'` or `overrideToolchain` to inject nightly rustfmt, in principle (i.e., keep things as they are). That should prevent us from opening some can of worms we don't know of yet.

Though, going further, we could also have a specific `rustfmt` override for the devShell function, which would allow us to ignore the toolchain's / scope's rustfmt in favor of a custom/nightly build in an easier way. At least such an approach would be more likely to work than having to consider multiple different toolchain / scope / ... combinations in `crane` itself (just delegate it to the user).

**Comment by ipetkov** [comment]
> Though, going further, we could also have a specific rustfmt override for the devshell function (and/or cargoFmt function), 

Could always `(craneLib.overrideScope (final: prev: { rustfmt = rustfmt-for-devshell; })).devshell { ... }` :wink:

**Comment by PgBiel** [comment]
> > Though, going further, we could also have a specific rustfmt override for the devshell function (and/or cargoFmt function),
> 
> Could always `(craneLib.overrideScope (final: prev: { rustfmt = rustfmt-for-devshell; })).devshell { ... }` 😉

Well... okay, you win. Haha
