### ISSUE TITLE
multi-target with fenix?

### ISSUE THREAD

**Issue by DavSanchez** [ipetkov/crane#393]
Hi,

Sorry this is not a bug or anything, feel free to close or point elsewhere. I'm checking the documentation regarding cross-compilation and I'm trying to have a multi-target setup so I can select what to target when doing `nix build ...`. 

[This example](https://crane.dev/examples/cross-rust-overlay.html) seems to set `crossSystem` early when setting `craneLib` so it's not really easy to set many targets without re-defining `pkgs` for each target package (and also the default package for local system builds, devShells, etc), so I was thinking on using `fenix` to have a toolchain with all the targets ready and then try to replicate the remaining pieces, but I'm struggling to make it work. After compiling the world, I find `can't find crate for 'core'` errors indicating that the target may not be installed, but I did add the targets to the toolchain via `fenix` and then did an `overrideToolchain`. I'm setting `craneLib` as `crane.lib.${localSystem}.overrideToolchain ...` so perhaps the problem lies there.

Does `crane` have a clean way to achieve this?

**Comment by dpc** [comment]
FWI, we do bunch of [fancy things with cross-compilation in Fedimint](https://github.com/fedimint/fedimint/blob/master/flake.toolchain.nix), but I was never able to get crossSystem to work with flakes + crane, and had to take care of a lot of details manually to get everything to work.

**Comment by ipetkov** [comment]
> After compiling the world, I find can't find crate for 'core' errors indicating that the target may not be installed

@DavSanchez if your invocation requires compiling `core`/`std` from scratch (e.g. if you are cross compiling to a less-mainstream target, i.e. one which does not have prebuilt versions distributed by the Rust project) you may be missing the `src` component?

I don't have a lot of experience with `fenix` so I can't speak for it, but I know with `oxalica/rust-overlay` you can set `extensions = [ "rust-src" ];` to pull in the standard library sources (which should help with compiling the crates if needed). There is also [this example](https://github.com/ipetkov/crane/blob/681ad0016630ded86c386a3dbcc13c702650ba08/examples/build-std/flake.nix) for building stdlib crates in case that's helpful!

**Comment by dpc** [comment]
@DavSanchez https://github.com/dpc/flakebox/blob/dev/docs/building-new-project.md

You can either try to use `flakebox` as is, or peak under the hood.

This issue can probably be closed. Nothing actionable in the crane itself.

**Comment by DavSanchez** [comment]
Good day everyone,

Thanks for all the inputs! I'm of the same opinion, this was more of a guidance request that has been answered already.

Best regards!
