### ISSUE TITLE
How to bypass cleanCargoToml for specific dependencies?

### ISSUE THREAD

**Issue by danjl1100** [ipetkov/crane#394]
I am getting a rustc error when building a crate with any dependencies that themselves depend on [document-features](https://lib.rs/crates/document-features)  (e.g. many parts of [embassy](https://github.com/embassy-rs/embassy)).

The issue seems to be that the `document_features!` proc-macro depends on "doc comments" being present in Cargo.toml at build time, whereas crane is stripping out comments (for better cache hits?).

I experimented with overriding crane's `cleanCargoToml` attribute, but it did not seem to apply to dependencies of the crate being built.   See further notes at the [reproducible example](https://github.com/danjl1100/example_uses_dep_using_document_features), which uses a [minimal dependency](https://github.com/danjl1100/example_uses_document_features) that itself depends on `document-features`.

<details>
<summary>Summary of rustc error message</summary>

More details at the README for the [reproducible example](https://github.com/danjl1100/example_uses_dep_using_document_features).

```
$ cargo c
+ command cargo c
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s

$ nix build
warning: Git tree '/home/user/the_bin' is dirty
error: builder for '/nix/store/bvizj8r1dbz8941pbvqr1s0s0qpr2w6z-the_bin-deps-0.1.0.drv' failed with exit code 101;
       last 10 log lines:
       >     Checking example_uses_document_features v0.1.0 (https://github.com/danjl1100/example_uses_document_features.git#a1ba56e5)
       > error: Could not find documented features in Cargo.toml
       >  --> /nix/store/680bw6m3wbvjim5qsymmllcbk61pf7v5-vendor-cargo-deps/6324285ea70798e13c0a2ff48894e089c59e1e9b1901e701033e48ef46db6c00/example_uses_document_features-0.1.0/src/lib.rs:2:10
       >   |
       > 2 | #![doc = document_features::document_features!()]
       >   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >   |
       >   = note: this error originates in the macro `document_features::document_features` (in Nightly builds, run with -Z macro-backtrace for more info)
       >
       > error: could not compile `example_uses_document_features` (lib) due to previous error
       For full logs, run 'nix log /nix/store/bvizj8r1dbz8941pbvqr1s0s0qpr2w6z-the_bin-deps-0.1.0.drv'.
error: 1 dependencies of derivation '/nix/store/x9ww0x9svbvfl7y1l3ni060pds2pf4ck-the_bin-0.1.0.drv' failed to build


$ cat /nix/store/680bw6m3wbvjim5qsymmllcbk61pf7v5-vendor-cargo-deps/6324285ea70798e13c0a2ff48894e089c59e1e9b1901e701033e48ef46db6c00/example_uses_document_features-0.1.0/Cargo.toml
[package]
name = "example_uses_document_features"
version = "0.1.0"
edition = "2021"

[dependencies]
document-features = "0.2.7"

[features]
feature = []


$ cat ~/.cargo/git/checkouts/example_uses_document_features-5fcd98ea203068e9/a1ba56e/Cargo.toml
[package]
name = "example_uses_document_features"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
document-features = "0.2.7"

[features]
## Documented
feature = []
```

The `## Documented` line is present in the git checkout (last output), but not in the cleanCargoToml version used internally by crane (second-to-last output).
</details>

<details>
<summary>Failed attempt to deactivate cleanCargoToml when the crate depends on `document-features`</summary>

```patch
-      craneLib = crane.lib.${system};
+      craneLib = crane.lib.${system}.overrideScope' (final: prev: {
+          cleanCargoToml = args: let
+            cleaned = prev.cleanCargoToml (pkgs.lib.traceVal args);
+            raw = builtins.readFile args.cargoToml;
+            original = builtins.fromTOML raw;
+            needs_original = pkgs.lib.hasAttr "document-features" cleaned.dependencies;
+          in
+            if needs_original
+            then (builtins.trace "original for ${cleaned.package.name} ITS DEPENDENCIES MATCHED!" original)
+            else (builtins.trace "cleaned for ${cleaned.package.name}" cleaned);
+        });
```

This runs, but does not seem to affect the handling of Cargo.toml for dependencies.
</details>

I would appreciate any help shedding light on possible solution or hack to get this working. :slightly_smiling_face:

**Comment by ipetkov** [comment]
Hi @danjl1100! The best option I can offer is utilizing [`mkDummySrc`'s `extraScript` parameter](https://github.com/ipetkov/crane/blob/681ad0016630ded86c386a3dbcc13c702650ba08/docs/API.md#optional-attributes-15) to inject in whatever arbitrary logic you'd like (e.g. copying in the original `Cargo.toml`, or injecting a dummy comment just for the deps-only build).

Otherwise there's no good way to retain comments (even all of them!) since the Nix implementation of parsing/serializing toml doesn't handle comments

**Comment by danjl1100** [comment]
Got it, I see how `extraDummyScript` in `buildDepsOnly` could allow me to modify the project's Cargo.toml.

Unfortunately, I need to edit the Cargo.toml of a git dependency.  It seems the dependencies' comments are stripped during `vendorCargoDeps`, specifically (since it is a git dependency) by the TOML merge in `downloadCargoPackageFromGit` calling `crane-resolve-workspace-inheritance`.

Poking around in the `extraDummyScript` argument to `buildDepsOnly` I'm not seeing the dependencies closure supplied by the `cargoVendorDir` argument.

How do I point the `buildDepsOnly` derivation to use a modified version of the vendored dependency? (with a feature comment injected in the Cargo.toml)
Alternatively, is there an argument for `vendorCargoDeps` that is similar to `extraDummyScript` to fixup the result?

**Comment by ipetkov** [comment]
Ah interesting! Those comments are being striped out [in this crane utility](https://github.com/ipetkov/crane/blob/9dae37b4a545f05aa70a2f048428c5196690c5a4/pkgs/crane-utils/src/bin/crane-resolve-workspace-inheritance.rs#L77-L84) which handles the workspace inheritance. I know there's the `toml_edit` crate which might be possible to use (as it would preserve all other comments in that Cargo.toml)

The other alternative is just like you mentioned: handle the dependency vendoring yourself; or write your own scripts to do any kind of post-processing on the vendored results and feed that into the derivation!

**Comment by danjl1100** [comment]
Through some trial and error, I found a way to patch the dependencies' Cargo.toml if they themselves depend on `document-features`.  It took me quite a bit to figure out that `config.toml` was the actual link to the "-deps" path in the nix store (as that also needed patching to use the modified vendor dir).

It's probably not as simple and compact as it could be, but this is what worked for me: https://github.com/danjl1100/example_uses_dep_using_document_features/commit/f248fad8c95fe9b6708f3cb33d41c7d7d2323665

I'll go ahead and close this issue, thanks again for helping me out!

--

Out of curiosity, would you be open to reviewing a PR to migrate to `toml_edit` in the crane utility you linked?  If so, I might start fiddling around with it.
