### ISSUE TITLE
Making your own lib and not overriding clippy makes clippy fail with incompatible versions

### ISSUE THREAD

**Issue by TheNeikos** [ipetkov/crane#43]
In my flake I have:

```nix
         craneLib = (crane.mkLib pkgs).overrideScope' (final: prev: {
            rustc = rustTarget;
            cargo = rustTarget;
            rustfmt = rustTarget;
          });
```

and in my checks:

```nix
 my-app-clippy = craneLib.cargoClippy {
              inherit cargoArtifacts src;
              cargoClippyExtraArgs = "-- --deny warnings";
            };
```

This gives the following error:

```
error[E0514]: found crate `std` compiled by an incompatible version of rustc
  |
  = help: please recompile that crate using this compiler (rustc 1.60.0) (consider running `cargo clean` first)
  = note: the following crate versions were found:
          crate `std` compiled by rustc 1.61.0 (fe5b13d68 2022-05-18): /nix/store/7nbm9f6mf8jh8ndxm243zbdjkdwwh7lr-rust-std-1.61.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-05b39ac0cb4c5688.rlib
          crate `std` compiled by rustc 1.61.0 (fe5b13d68 2022-05-18): /nix/store/7nbm9f6mf8jh8ndxm243zbdjkdwwh7lr-rust-std-1.61.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-05b39ac0cb4c5688.so
          crate `std` compiled by rustc 1.61.0 (fe5b13d68 2022-05-18): /nix/store/7nbm9f6mf8jh8ndxm243zbdjkdwwh7lr-rust-std-1.61.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-df6036c77d75ce21.rlib
```

Adding clippy to the mkLib makes it work again.

While I understand that this error is of my making, it is also somewhat intransparent if I didn't know what went wrong. Maybe the lib can check that clippy is being called on the right version before and throw a better message, or mkLib makes sure that they are all the same version (with a helper function maybe?)

**Comment by ipetkov** [comment]
Thanks for the report @TheNeikos, this is an interesting idea!

I'm not really sure what would be a good way to even detect this at evaluation time. Even if we tried looking at the version strings I wonder what kind of edge cases would be hit for even more custom toolchain setups (e.g. projects having their own patched versions of clippy whose version number is incorrect, or a project explicitly pinning to a specific clippy version which builds against a different `target` directory without conflicts, etc.)

**Comment by TheNeikos** [comment]
I was thinking along the lines of `mkLibSimple rustTarget` which would be the equivalent of
```nix
         craneLib = (crane.mkLib pkgs).overrideScope' (final: prev: {
            rustc = rustTarget;
            cargo = rustTarget;
            rustfmt = rustTarget;
# ... Other scope parts
          });
```

aka, override every part

**Comment by ipetkov** [comment]
Aha, thanks for elaborating, I understand your suggestion now! I'll see what I can do
