### ISSUE TITLE
Dependencies using `lints` cannot be built

### ISSUE THREAD

**Issue by rvolosatovs** [ipetkov/crane#480]
Rust 1.74 added support for `lints` attribute in Cargo manifest (https://blog.rust-lang.org/2023/11/16/Rust-1.74.0.html#lint-configuration-through-cargo), which causes incompatibility it seems, e.g.:
```
failed to update replaced source https://github.com/bytecodealliance/wasmtime?branch=release-16.0.0#759aa585
       >
       > Caused by:
       >   failed to parse manifest at `/nix/store/5qrfydk8pcql8ivlx568a2s6asa40y7v-vendor-cargo-deps/6fe5d6a99257bab41b19f2932c7a0b6aa9306e7fabbef3b691e1c6cb8654cbad/wasmtime-16.0.0/Cargo.toml`
       >
       > Caused by:
       >   error inheriting `lints` from workspace root manifest's `workspace.lints`
```

**Comment by rvolosatovs** [comment]
It's very likely, however, that the issue is that the package is not compatible with `cargo vendor`, I'll have to take a better look tomorrow

**Comment by ipetkov** [comment]
Hi @rvolosatovs thanks for the report! I think we need to teach [`crane-resolve-workspace-inheritance.rs`](https://github.com/ipetkov/crane/blob/62fc1a0cbe144c1014d956e603d56bf1ffe69c7d/pkgs/crane-utils/src/bin/crane-resolve-workspace-inheritance.rs#L93-L97) to handle merging in the `[lints]` table which it knows nothing about today
