### ISSUE TITLE
Add info to `Cargo.toml is not at the source root` page

### ISSUE THREAD

**Issue by johnbchron** [ipetkov/crane#509]
I was encountering an issue where I was getting this error, and I eventually found out that it was because in the [github official rust `.gitignore` file](https://github.com/github/gitignore/blob/main/Rust.gitignore), the `Cargo.toml` is ignored, so Nix's git-based file copying couldn't find it.

Maybe we could add a note about this on the `Cargo.toml is not at the source root` page? It's not essential, but it would have helped me.

Thanks again for this wonderful tool!

**Comment by ipetkov** [comment]
Hey @johnbchron thanks for the report! I agree that it would be helpful to have a message hint that `Cargo.lock` ought to be staged (and not .gitignored) if the file can't be found!

Feel free to open a PR for it, otherwise I'll try to get to it sometime!
