### ISSUE TITLE
Optimize Crane to Avoid Full Rebuilds on Single Dependency Updates

### ISSUE THREAD

**Issue by noverby** [ipetkov/crane#528]
Crane currently triggers a full rebuild of all dependencies, even when only a single dependency is updated. This behavior significantly impacts development efficiency in large monorepo Cargo projects, where rebuilding all dependencies can be prohibitively time-consuming.

Is there anything on the roadmap to improve on this?

**Comment by dpc** [comment]
Probably not. There are existing issues about it.

I'd advise that [generally developers should be using nix dev shell and not have to go through nix build during normal work](https://github.com/ipetkov/crane/issues/366#issuecomment-1675422275).

**Comment by FireFragment** [comment]
> @ipetkov There's no way out of this except for splitting up your build into multiple derivations and cleaning our any "unused" bits from Cargo.lock manually.

Is there some conceptual reason crane doesn't work this way and builds all dependencies at once? Or is it just because this way it's easier to implement? Because to me, that seems like a nice solution.

**Comment by dpc** [comment]
It's harder as it requires basically re-implementing what cargo is doing.

Also, by storing all dependencies as one big artifact everything can be compressed together in the store, saving storage and making things actually faster.

In practice changes to `Cargo.lock` are often bulky anyway. Changes to one dependency can cause rebuilds for many dependent dependencies, and when people update dependencies they often do it in bulk as well (one big `cargo update`).
