### ISSUE TITLE
Tags with `+suffix` breaking vendoring?

### ISSUE THREAD

**Issue by dpc** [ipetkov/crane#549]
We've tried to use a dependency in `Cargo.lock` that refers to a git repo with tag that contained `+suffix`, and we got a weird error:

```
pkgs-group-ci-deps> Caused by:
pkgs-group-ci-deps>   failed to load source for dependency `repo-core`
pkgs-group-ci-deps> Caused by:
pkgs-group-ci-deps>   Unable to update https://github.com/repo/repo-repo?tag=v0.3.0-alpha.0+suffix
pkgs-group-ci-deps> Caused by:
pkgs-group-ci-deps>   the source https://github.com/repo/repo-fedi?tag=v0.3.0-alpha.0+suffix requires a lock file to be present first before it can be
pkgs-group-ci-deps>   used against vendored source code
pkgs-group-ci-deps>   remove the source replacement configuration, generate a lock file, and then
pkgs-group-ci-deps>   restore the source replacement configuration to continue the build
```

`cargo build` and `cargo vendor` work locally just fine. After changing the tag name to not contains `+suffix`, the problem went away.

**Comment by ipetkov** [comment]
Hmm interesting, there's two parts of the code which come to mind:

1. Parsing the git dependency in Cargo.lock (though nothing about the code immediately jumps out as the culprit): https://github.com/ipetkov/crane/blob/10484f86201bb94bd61ecc5335b1496794fedb78/lib/vendorGitDeps.nix#L42-L75
2. How we specify the tag when asking Nix to download it: https://github.com/ipetkov/crane/blob/10484f86201bb94bd61ecc5335b1496794fedb78/lib/vendorGitDeps.nix#L91-L104

Do you have a reproduction I can test out further?

**Comment by avnik** [comment]
@ipetkov one more repro -- this time with branch name
https://github.com/avnik/ghaf-givc/tree/avnik/listeners%2Bvsock%2Btonic

**Comment by thecaralice** [comment]
This is a bug in cargo, not in crane. See rust-lang/cargo#14584.

**Comment by thecaralice** [comment]
Update: this issue has already been fixed in cargo, but the lockfile needs to be updated to `version = 4`, as mentioned in https://github.com/rust-lang/cargo/issues/14584#issuecomment-2369414962.

**Comment by ipetkov** [comment]
Thank you for the reproduction @avnik and thank you for the insight that this is a cargo bug @thecaralice !

Sounds like there isn't anything we can do on the `crane` side here. Anyone who hits this will need to manually update their `Cargo.lock` file to have `version = 4` (until cargo is updated to migrate from v3 to v4 in the future)
