### ISSUE TITLE
Way to build each workspace member as separate derivation

### ISSUE THREAD

**Issue by lblasc** [ipetkov/crane#55]
We have big cargo workspace with lot of crates depending on each other. Building whole workspace is ok while developing but in actual deploy we would like to build only crates which are used not the whole workspace.
Currently we are using crate2nix which can output each workspace member as separate derivation, can crane be used in this way ?

Thanks for working on this!

**Comment by dpc** [comment]
* https://github.com/ipetkov/crane/discussions/31
* https://github.com/rustshop/loglog/blob/87b358a4e69eb80c8ae5e3c8d6caedb54541ba22/flake.nix#L83
* https://github.com/ipetkov/crane/discussions/51
