### ISSUE TITLE
Not possible to override crane-utils or its dependencies

### ISSUE THREAD

**Issue by fracek** [ipetkov/crane#551]
Hello, I need to compile my project using an older `nixpkgs` (23.05). The issue I'm facing is that it tries to compile `crane-utils` using nix `rustPlatform` which uses Cargo 1.69 but the minimum required version to compile `crane-utils` is 1.70.

I haven't figured out how to override the `rustPlatform` used to build `crane-utils`. If I override `crane-utils` in an overlay it's not used by crane anyway.

[I made a minimal repository to reproduce the issue here](https://github.com/fracek/crane-with-nix-23-05)

**Comment by ipetkov** [comment]
Hi @fracek thanks for the report! At this time we don't have a good way to override/overlay crane-utils: https://github.com/ipetkov/crane/blob/f1dabc4abaa6e1ef4ef92d046aced96d1e94dc14/lib/downloadCargoPackageFromGit.nix#L12

In the mean time you can get unblocked by either using `crane-0.15.1` or using the `23.11` release branch. `23.05` is EOL and we dropped support for it in `crane-0.16.0`

**Comment by ipetkov** [comment]
Overriding `craneUtils` will become possible once https://github.com/ipetkov/crane/pull/652 lands!
