### ISSUE TITLE
Cargo dep with missing locked revision fails with unclear error message

### ISSUE THREAD

**Issue by dpc** [ipetkov/crane#57]
After using `tokio-uring = { version = "0.3.0", git = "https://github.com/tokio-rs/tokio-uring" }` I was getting:

```
> nix build .#loglogd                                                                                                                                                              
warning: Git tree '/home/dpc/lab/loglog' is dirty                                                                                                                                  
error: unknown hash algorithm 'https'                                                    
Try 'nix --help' for more information.     
```

I had to:

```
--- a/server/Cargo.toml
+++ b/server/Cargo.toml
@@ -25,7 +25,7 @@ tokio = { version = "1.19.2", features = ["macros", "rt", "rt-multi-thread", "si
 thiserror = "1.0.31"
 num_enum = "0.5.7"
 nix = { version = "0.24.2", features = [ "zerocopy" ]}
-tokio-uring = { version = "0.3.0", git = "https://github.com/tokio-rs/tokio-uring" }
+tokio-uring = { version = "0.3.0", git = "https://github.com/tokio-rs/tokio-uring", branch = "master" }
 binrw = "0.9.2"
 typed-builder = "0.10.0"
 derive_more = "0.99.17"
```

to get it to build again.

**Comment by ipetkov** [comment]
Thanks for the report @dpc! Do you have a flake which can reproduce the error you hit?

The `Cargo.lock` file will include a particular commit of the git checkout (even without specifying a branch). The test suite [already has a test case for git dependency without a branch/tag/rev](https://github.com/ipetkov/crane/blob/57448afcec5880a7d770857b4de4cfbe90808d8e/checks/simple-git/Cargo.toml#L6-L8). I also tried changing that test to include `tokio-uring = { version = "0.3.0", git = "https://github.com/tokio-rs/tokio-uring" }` but everything built just fine so I can't reproduce the issue

**Comment by dpc** [comment]
https://github.com/rustshop/loglog/commit/c08ff81e8a24bd83195df421e13be69099f048b3

this was the commit that was failing both locally and CI: https://github.com/rustshop/loglog/runs/7703607950?check_suite_focus=true

The followup commit fixed it: https://github.com/rustshop/loglog/actions/runs/2808339275

**Comment by ipetkov** [comment]
Hmm this looks really weird, it's as if cargo failed(?) to write a git revision in the `Cargo.lock `file.

Changing the branch appears to have fixed things by forcing cargo to append the revision in the lock file. I was also able to fix things by running `cargo update -p tokio-uring` which also seemed to make cargo add a revision to the lock file :thinking: 

We _must_ have a revision present in the lock file because nix wants to check out a specific commit. If the `Cargo.lock` file is "invalid" in such a manner then it seems like the best thing we can do is throw a descriptive error to make it easier to resolve

**Comment by dpc** [comment]
Oh, I see. Now that I think about it - I might have accidentally trigger this state manually, by messing with this `Cargo.lock` in some weird ways.

A better error message would be great, but I guess it might be just invalid.

**Comment by ipetkov** [comment]
Good diagnostics never hurt! I've opened #58 to improve the situation here :smile:
