### ISSUE TITLE
Warn if using old nixpkgs

### ISSUE THREAD

**Issue by TheNeikos** [ipetkov/crane#570]
I just went into an old repo of mine where I override the nixpkgs input of crane, and update the inputs.

I was using nixos-22.11. However, I encountered the warning of #550 as well as an error when building the clippy derivation.

Clearly the correct thing here is to update, and I happened to deduce it from #550 as I also was using `overrideToolchain`.

Maybe crane could add some warnings(/asserts?) if it detects that a too old nixpkgs is being used as its input (due for example being overriden) and tell the user that it is unsupported and that any errors they encounter with crane are probably due to this.

This way they might be spared of trying to find out why things suddenly don't build anymore!

**Comment by ipetkov** [comment]
Thanks for the suggestion this is a great idea! I think a warning ought to be good enough (if things _happen_ to work with an older nixpkgs there is no need to do a hard assert, but at least the warning will give an indication something might be off)

I'll put a PR up in a minute!

**Comment by TheNeikos** [comment]
Awesome! Thank you
