### ISSUE TITLE
Missing documentation: plain cargo workspaces example

### ISSUE THREAD

**Issue by lolbinarycat** [ipetkov/crane#585]
a very common pattern is to split up a project into several crates, usually a library and an executable, in order to separate the cli logic from the application logic.

crane provides an example of using workspaces with trunk, but does not show how to use workspaces for anything that isn't a webapp.

**Comment by ipetkov** [comment]
Thanks for the suggestion @lolbinarycat ! I've added an example in https://github.com/ipetkov/crane/pull/597
