### ISSUE TITLE
Support for Package Options (Usable With `.override`)

### ISSUE THREAD

**Issue by zedseven** [ipetkov/crane#586]
I'm not sure if I've missed something, if this isn't possible, etc., but I wanted to open the discussion.

My Rust program is a GUI application with support for X11 and Wayland.

Naturally, on NixOS, those need to be specified in `buildInputs` so that Nix knows they're required, but I want the final package to allow the user to disable the platforms they don't need by overriding the package.

Normally, I'd do this with something like the following:
```nix
{
  lib,
  stdenv,
  x11Support ? true,
  waylandSupport ? true,
  ...
}:
stdenv.mkDerivation {
  # ...

  buildInputs = [
    # ...
  ] ++ lib.optionals x11Support [
    # ...
  ] ++ lib.optionals waylandSupport [
    # ...
  ]

  # ...
}
```

But I can't find a way to have similar options with `craneLib.buildPackage`, since it seems to only accept a set, and doesn't accept a function.

Is this possible?

I'm also open to other alternatives, if there's a better approach or best practice that I'm not aware of.

**Comment by ipetkov** [comment]
Hi @zedseven thanks for the report!

The short answer is that you should wrap the call to `craneLib.buildPackage` in a separate file and use `callPackage` on that file. Then you can use `.override { x11Support = false; }` (or equivalent) to tailor things further.

I've also opened https://github.com/ipetkov/crane/pull/596 to document some examples on this, so hope that helps! (Feel free to reopen if you have any other suggestions to update the docs)
