### ISSUE TITLE
Binaries missing from `$out/bin/`

### ISSUE THREAD

**Issue by samuela** [ipetkov/crane#589]
Similar to https://github.com/nix-community/naersk/issues/324, I'm finding that my "api" binary is missing from $out/bin when building with crane. Running `cargo build` manually creates `target/debug/api`, but I'm not seeing it compiled or generated by crane.

Perhaps this is some kind of issue pervasive to the nix rust builders?

**Comment by dpc** [comment]
Is it in the `./target` during Nix build? You can add `ls ...` somewhere in a preInstall hook or something like that.

**Comment by samuela** [comment]
I had to `git add src/bin/api.rs`... damn flake/git coupling!
