### ISSUE TITLE
Crane / nix flake delaying the stdout from the cargo?

### ISSUE THREAD

**Issue by dpc** [ipetkov/crane#69]
I've noticed both locally and in CI that the output is delayed. When a large package is being built what is being displayed is actually:

```
   Compiling proc-macro-error v1.0.4
```

where `proc-maco-error` is just an arbitrary crate that happens to be right before the the crate that actually takes a long time to build. It's mildly annoying, and also confusing.

Initially I thought it's because of the progress-bar, but I tried to disable it and it doesn't make a difference.

**Comment by ipetkov** [comment]
`crane` doesn't capture the output of cargo, so it goes directly to nix.

I believe when the output is not a tty cargo will print out the name of a crate when it starts compiling it, but doesn't print out anything when the crate finishes so it may be hard to tell which crate is still being built. When cargo's output is going directly to a terminal it will render which crates are actively being built, but this won't show up by default when nix is capturing the logs.

Unfortunately I don't know if anything that can be done here
