### ISSUE TITLE
Private registry dependency in virtual workspace generates malformed config.toml

### ISSUE THREAD

**Issue by Palladinium** [ipetkov/crane#702]
**Describe the bug**
I've tried setting up a Nix flake based on the [Quick Start for a workspace](https://crane.dev/examples/quick-start-workspace.html), while also adding a private registry. The flake file is mostly the same as the quick start one, with the following line:

```nix
craneLib = crane.mkLib pkgs;
```

replaced with this, to enable a private registry (some parts redacted):

```nix
craneLibBase = crane.mkLib pkgs;
registryToken = builtins.readFile ./secrets/registry-token;
craneLib = craneLibBase.appendCrateRegistries [
  (craneLibBase.registryFromSparse {
    indexUrl = "http://host.domain:1234/index/";
    configSha256 = "<sha256>";
    fetchurlExtraArgs = {
      curlOptsList = [
        "-H"
        "Authorization: ${registryToken}"
      ];
    };
  })
];
```

The only other changes from the quick start example involve changing the package and crate names to match my workspace layout.

For reference, outside of Nix I normally just have this in my `~/.cargo/config.toml`:

```toml
[registries]
myrepo = { index = "sparse+http://host.domain:1234/index/" }
```

And a corresponding `credentials.toml` set up. The crate in the workspace refers to its dependency as:
```toml
dependencyname = { registry = "myrepo", version = "0.1.0" }
```

The private registry dependencies get pulled and compiled successfully, but I run into this error:
```
error: builder for '/nix/store/a79k1hs64lf2s2pqnvaxs6rkh2fsh97k-cargo-package-deps-0.1.0.drv' failed with exit code 101;
       last 25 log lines:
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/m7gn818lw8pzj3gpn7qyajmci7n0nl5x-source
       > source root is source
       > Running phase: patchPhase
       > Executing configureCargoCommonVars
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > will append /build/source/.cargo-home/config.toml with contents of /nix/store/5bm2b5cvn1ywly38mf95q2qqnmw776xq-vendor-cargo-deps/config.toml
       > default configurePhase, nothing to do
       > Running phase: buildPhase
       > ++ command cargo --version
       > cargo 1.80.0 (376290515 2024-07-16)
       > ++ command cargo check --release --locked --all-targets
       > error: could not load Cargo configuration
       >
       > Caused by:
       >   could not parse TOML configuration in `/build/source/.cargo-home/config.toml`
       >
       > Caused by:
       >   TOML parse error at line 8, column 13
       >     |
       >   8 | [source.http://host.domain:1234/index/]
       >     |             ^
       >   invalid table header
       >   expected `.`, `]`
       For full logs, run 'nix-store -l /nix/store/a79k1hs64lf2s2pqnvaxs6rkh2fsh97k-cargo-package-deps-0.1.0.drv'.
error: 1 dependencies of derivation '/nix/store/pn6vf1b6rmbp3ryi3c1p0ify9fqx4b1k-cratename-0.1.0.drv' failed to build
```

The `config.toml` in question looks like this:
```toml
[source.nix-sources-911ab032f2ab988395c534628be5bc0dd22d9ba803bf4d3780f9e3e9e5e5b994]
directory = "/nix/store/5bm2b5cvn1ywly38mf95q2qqnmw776xq-vendor-cargo-deps/911ab032f2ab988395c534628be5bc0dd22d9ba803bf4d3780f9e3e9e5e5b994"
[source.nix-sources-c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0]
directory = "/nix/store/5bm2b5cvn1ywly38mf95q2qqnmw776xq-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0"
[source.crates-io]
registry = "https://github.com/rust-lang/crates.io-index"
replace-with = "nix-sources-c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0"
[source.http://host.domain:1234/index/]
registry = "sparse+http://host.domain:1234/index/"
replace-with = "nix-sources-911ab032f2ab988395c534628be5bc0dd22d9ba803bf4d3780f9e3e9e5e5b994"
```

This seems broken to me - the colon in the URL is not allowed in a key name in TOML.
I think this is emitted by this line: https://github.com/ipetkov/crane/blob/7e4586bad4e3f8f97a9271def747cf58c4b68f3c/lib/vendorCargoRegistries.nix#L127

Where `escapeShellArg` is not successfully escaping the URL because the escaping rules for TOML are more restrictive than those for Bash.

By the way, it seems odd that `name` is evaluating to a URL, should it perhaps be evaluating to `myrepo`? One thing I noticed is that the `myrepo` name is never associated with its URL in the Nix flake, while it is in the native setup. I presume `crane` can infer that from the Cargo.lock file, but I'm not sure.

It may be worth noting is that the workspace is virtual, and I had to add this to the workspace `Cargo.toml` to get rid of a few warnings, as `crane` would not find the version from the individual crates:

```toml
[workspace.package]
version = "0.1.0"
```

It's also very possible that I simply made a mistake somewhere, as I'm quite new to Nix. If that's the case, then I think the error message could be improved.

**Reproduction**
I don't have a minimal setup for reproduction yet, because it involves owning and running a private registry, which is non-trivial (the flake fails at an earlier step if the registry is unreachable). I'll work on getting a minimal repro case working from scratch soon.

**Comment by ipetkov** [comment]
Hi @Palladinium thanks for the report!


> By the way, it seems odd that `name` is evaluating to a URL, should it perhaps be evaluating to `myrepo`?

Yes I think you are right, that should be showing up as `myrepo` and not the URL. Maybe we have a bug with the processing logic :thinking: 

> For reference, outside of Nix I normally just have this in my `~/.cargo/config.toml`:

Just double checking, do you have the same contents defined in the project's `.cargo/config.toml`? During the Nix evaluation we can't actually read `~/.cargo/config.toml` (or any other parent directory's `.cargo/config.toml`) so this does need to be defined somewhere within the repo

Also as a sanity check, could you run `cargo vendor 2>/dev/null` and share the output here? I just want to double check what cargo expects the configs to look like (and whether there is any toml sensitization happening or if we're pulling the wrong value somewhere)

> It may be worth noting is that the workspace is virtual, and I had to add this to the workspace `Cargo.toml` to get rid of a few warnings,

These warnings are unrelated to the registry issue at hand so we can ignore them here (feel free to open a separate discussion if you have questions though!)

---

> I don't have a minimal setup for reproduction yet, because it involves owning and running a private registry, which is non-trivial

If you could give me the following, it might help me narrow down the problem:
1. A minimal reproduction of your configs (namely, I want to see how the registry urls are defined, they can be dummy urls, so long as i can trace them during the evaluation)
2. A minimal version of `Cargo.toml`, `Cargo.lock`, and `.cargo/config.toml`. Again, feel free to replace the real urls with a dummy domain, but as long as everything else maps accordingly
3. the output of `cargo vendor 2>/dev/null` as mentioned above

**Comment by Palladinium** [comment]
> Just double checking, do you have the same contents defined in the project's .cargo/config.toml? During the Nix evaluation we can't actually read ~/.cargo/config.toml (or any other parent directory's .cargo/config.toml)

I only have a `~/.cargo/config.toml`, and I don't think it's being read by a `nix build`. If I modify it and re-run `nix build` the nix store paths and the URLs in the error stay the same. I tried copying it as a `.cargo/config.toml` in my repo, both at the virtual workspace URL and in the individual crate directories, but that had the same result (same store paths, no changes in output even when modified). I double-checked after running `nix-store --gc`, just in case, and got the same results.

I think the only place the URLs for the registry are being read from is the `Cargo.lock` file, at least during a `nix build`. I suspect that a `nix shell` would pick up on the local `config.toml`, but I'm not sure since I haven't tried setting one up yet. I've already done development on this registry before using Nix, so my `Cargo.lock` already has the registry URL baked in, see the snippet below.

> 1. A minimal reproduction of your configs (namely, I want to see how the registry urls are defined, they can be dummy urls, so long as i can trace them during the evaluation)
> 2. A minimal version of Cargo.toml, Cargo.lock, and .cargo/config.toml. Again, feel free to replace the real urls with a dummy domain, but as long as everything else maps accordingly

`~/.cargo/config.toml` and `.cargo/config.toml`
```
[registry]
global-credential-providers = ["cargo:token"]

[registries]
myrepo = { index = "sparse+http://host.domain:1234/index/" }
```

`Cargo.toml` at the virtual workspace root
```
[workspace]
members = [
    "hakari-hack",
    "foo",
    "foo-api",
    "foo-cli"
]
resolver = "2"

# This is to fix one of the warnings about not finding a version number
[workspace.package]
version = "0.1.0"

[profile.release]
debug = 1
```

`foo/Cargo.toml`, the only one using a private registry dependency
```
[package]
name = "foo"
version = "1.0.0"
edition = "2021"

[dependencies]
my_private_crate = { registry = "myrepo", version = "0.1.0" }
foo-api = { path = "../foo-api", default-features = false }

# CUT: Many crates.io dependencies, some feature flag definitions
```

`Cargo.lock`
```
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

# CUT: Many crates.io dependencies

[[package]]
name = "my_private_crate"
version = "0.1.0"
source = "sparse+http://host.domain:1234/index/"
checksum = "big checksum string"
dependencies = [
  # CUT: Many crates.io dependencies
];

# CUT: Many more crates.io dependencies
```

> 3. the output of cargo vendor 2>/dev/null as mentioned above

```
[source.crates-io]
replace-with = "vendored-sources"

[source."sparse+http://host.domain:1234/index/"]
registry = "sparse+http://host.domain:1234/index/"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
```

I tried to preserve all the relevant parts from configs, it's a bit hard because the crates have a lot of transitive dependencies so the `Cargo.toml` and `Cargo.lock` files are very large.

**Comment by ipetkov** [comment]
Hi @Palladinium thanks for the sample data!

> I tried copying it as a `.cargo/config.toml` in my repo, both at the virtual workspace root and in the individual crate directories, but that had the same result

Did you, by any chance, remember to `git add -N .cargo/config.toml` before trying to build again?

Here's an interesting observation I had: when adding the example files above to a directory (and staging it with git so the flake evaluation would see it), the vendor config would include `[source.myrepo]`. However, if I removed `myrepo = { index = "sparse+http://host.domain:1234/index/" }` from `.cargo/config.toml`, then the vendor config would result in `[source.http://host.domain:1234/index/]`. I suspect this might be the case for your project as well!

---

File inclusion/staging bugs aside, I think we should ensure that the registry name/url is properly escaped before rendering it to TOML (`escapeShellArg` isn't enough here). I'm not certain that would result in a valid config that is accepted by cargo (e.g. because the `Cargo.toml` files would probably be referring to a non-existent registry), but that would lead to much better error messages than malformed TOML!

I have a work in progress on addressing the escaping issues; will try to wrap it up sometime this week

**Comment by ipetkov** [comment]
I did some more testing here, looks like if the registry definition is missing from `.cargo/config.toml` cargo will refuse to build (`cargo vendor` also fails). Using `dependencies.foo = {version = "*", registry = "https://example.com" }` in `Cargo.toml` also fails as cargo expects this to be a registry name (i.e. only alphanumeric chars along with `-` and `_`). I've added some better warnings in https://github.com/ipetkov/crane/pull/716 in case the `.cargo/config.toml` isn't being picked up (e.g. it's missing or it isn't staged with git) which should help highlight the issue!

I've also changed the vendoring logic to avoid creating malformed TOML format, so at least the appropriate cargo error should surface if anyone hits this in the future

**Comment by Palladinium** [comment]
> Did you, by any chance, remember to `git add -N .cargo/config.toml` before trying to build again?

Ah, good catch, I did not :sweat_smile: Adding it fixes the issue! Thank you for improving the diagnostics, that's appreciated.

**Comment by Palladinium** [comment]
> Did you, by any chance, remember to git add -N .cargo/config.toml before trying to build again?

Ah, good catch, I did not :sweat_smile:  Adding it fixed the vendored TOML, although now I'm running into other issues. I'll keep digging into them, and I'll open a separate issue if I hit a dead end.

It might also be worth mentioning the `.cargo/config.toml` in the example for using alternate registries, the provided `nix-init` includes one but the manual steps below don't, which is why I originally missed that step.

**Comment by ipetkov** [comment]
Ah great point, I've added a note in https://github.com/ipetkov/crane/pull/721 which should helpfully nudge folks in the right direction and avoid the pitfall you hit!
