### ISSUE TITLE
`craneLib.cargoDoc` cannot generate documentation for proc-macros

### ISSUE THREAD

**Issue by szg251** [ipetkov/crane#707]
**Describe the bug**

I have two packages, one of them is a conventional Rust library, the other is a proc-macro library. Both are correctly documented.
I can generate documentation for the first one, but the other one fails:

```
lbr-prelude-derive-doc> Running phase: buildPhase
lbr-prelude-derive-doc> ++ command cargo --version
lbr-prelude-derive-doc> cargo 1.78.0 (54d8815d0 2024-03-26)
lbr-prelude-derive-doc> ++ command cargo doc --release --locked --no-deps
lbr-prelude-derive-doc>     Checking unicode-ident v1.0.12
lbr-prelude-derive-doc>     Checking itoa v1.0.9
lbr-prelude-derive-doc>     Checking ryu v1.0.15
lbr-prelude-derive-doc>     Checking once_cell v1.18.0
lbr-prelude-derive-doc>     Checking glob v0.3.1
lbr-prelude-derive-doc>     Checking dissimilar v1.0.7
lbr-prelude-derive-doc>     Checking termcolor v1.3.0
lbr-prelude-derive-doc>    Compiling serde v1.0.188
lbr-prelude-derive-doc>    Compiling serde_json v1.0.107
lbr-prelude-derive-doc>    Compiling trybuild v1.0.85
lbr-prelude-derive-doc>    Compiling syn v2.0.38
lbr-prelude-derive-doc>     Checking proc-macro2 v1.0.69
lbr-prelude-derive-doc>     Checking quote v1.0.33
lbr-prelude-derive-doc>    Compiling serde_derive v1.0.188
lbr-prelude-derive-doc>     Checking basic-toml v0.1.4
lbr-prelude-derive-doc>  Documenting lbr-prelude-derive v0.1.1 (/private/tmp/nix-build-lbr-prelude-derive-doc-0.1.1.drv-0/lbr-prelude-derive-build-env)
lbr-prelude-derive-doc>     Finished `release` profile [optimized] target(s) in 17.49s
lbr-prelude-derive-doc> Running phase: installPhase
lbr-prelude-derive-doc> mv: cannot stat 'target/x86_64-apple-darwin/doc': No such file or directory
error: builder for '/nix/store/0kpbgba51jr34fpbpmv54mbgjlzd6y3m-lbr-prelude-derive-doc-0.1.1.drv' failed with exit code 1;
```

Logs of other packages have a line starting with `Generated /nix/store/...`, which is missing here.

I also tried to run the `cargo doc --release --locked --no-deps` directly, I get:

```
Documenting lbr-prelude-derive v0.1.1 (/Users/gergo/Dev/mlabs/lambda-buffers/runtimes/rust/lbr-prelude-derive)
    Finished `release` profile [optimized] target(s) in 1.26s
   Generated /Users/gergo/Dev/mlabs/lambda-buffers/runtimes/rust/lbr-prelude-derive/target/doc/lbr_prelude_derive/index.html
```

Also, the same library has auto-generated docs on https://docs.rs/lbr-prelude-derive/0.1.1/lbr_prelude_derive/

**Reproduction**
1. Implement a library using `proc-macro = true` in Cargo.toml
2. Use `craneLib.cargoDoc` to generate rustdoc

Alternatively, this package is accessible here https://github.com/mlabs-haskell/lambda-buffers/tree/szg251/flake-lang-update/runtimes/rust/lbr-prelude-derive
with the rustFlake definition is here: https://github.com/mlabs-haskell/flake-lang.nix/blob/main/flake-lang/rust/flake-rust.nix#L203-L206
And the derivation can be built by running `nix build .#lbr-prelude-derive-rust-doc -L`

**Comment by ipetkov** [comment]
Hi @szg251 thanks for the report and the reproduction!

It looks like your configuration explicitly sets `CARGO_BUILD_TARGET` which causes the `cargoDoc` script to look for `./target/$CARGO_BUILD_TARGET/doc`: https://github.com/ipetkov/crane/blob/6b40cc876c929bfe1e3a24bf538ce3b5622646ba/lib/cargoDoc.nix#L28

Yet it seems like cargo insists on outputting docs in `./target/doc` for non-cross-compiled docs, even when `$CARGO_BUILD_TARGET` is set :thinking: 

Anyway I've added a fallback check in https://github.com/ipetkov/crane/pull/708 which I think should fix the problem!
