### ISSUE TITLE
Build fails on nix-on-droid

### ISSUE THREAD

**Issue by bemyak** [ipetkov/crane#734]
**Describe the bug**

I'm trying to build a package inside a [nix-on-droid](https://github.com/nix-community/nix-on-droid) environment, but the build fails on the installation phase:
```
Running phase: installPhase
@nix { "action": "setPhase", "phase": "installPhase" }
searching for bins/libs to install from cargo build log at cargoBuildLog3y5q.json
installing /tmp/nix-build-zola-new-0.1.6.drv-0/source/target/release/zola-new
searching for bins/libs complete
stripping references to cargoVendorDir from:
tee: /dev/fd/3: Permission denied
```
(the origin is [here](https://github.com/ipetkov/crane/blob/a4ca93905455c07cb7e3aca95d4faf7601cba458/lib/setupHooks/removeReferencesToVendoredSourcesHook.sh#L12) I believe)

Seems like it's not allowed to write to `/dev/fd/3` on Android. Can this be avoided somehow?

I realize that it's a pretty niche use case, but it would be so cool to get it working :slightly_smiling_face: 

**Reproduction**
1. Install [nix-on-droid](https://github.com/nix-community/nix-on-droid)
2. Try to build any rust package (I'm building https://gitlab.com/bemyak/zola-new)

(NB: The process takes _hours_ because of how proot is slow)

**Comment by bemyak** [comment]
Thanks! I've created this issue: https://github.com/nix-community/nix-on-droid/issues/423

**Comment by ipetkov** [comment]
Hi @bemyak thanks for the report! It was pretty easy to avoid referencing `/dev/fd` directly (in favor of `cat` with a redirection) so this should be fixed with https://github.com/ipetkov/crane/pull/737

**Comment by bemyak** [comment]
It works now, thanks a lot 🎉
