### ISSUE TITLE
buildTrunkPackage fails with trunk from nixpkgs

### ISSUE THREAD

**Issue by antifuchs** [ipetkov/crane#735]
**Describe the bug**

Using buildTrunkPackage with trunk 0.21.1 from nixpkgs-unstable results in an unfortunate error when the profile that's being built is `release`:

```
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
++ command cargo --version
cargo 1.82.0 (8f40fc59f 2024-08-21)
error: invalid value './index.html' for '--release [<RELEASE>]'
  [possible values: true, false]
```

That's because buildTrunkPackage passes `--release` ([here](https://github.com/ipetkov/crane/blob/master/lib/buildTrunkPackage.nix#L87C20-L87C29)) and trunk requires `--release=true` now (I suspect introduced in [this change](https://github.com/trunk-rs/trunk/commit/265599c4f2725b0614f4b74a555f3cb4382f4c3e#diff-46230eb6eb9a3792464a39b022f624c28ce91fed38482b30f47f483f7ef14967R24)).

I've reported this to the trunk maintainers at https://github.com/trunk-rs/trunk/issues/908, but I suspect crane might want to switch to `--release=true` instead. What do you think?

**Reproduction**

Using the example from https://crane.dev/examples/trunk.html with a trunk from this nixpkgs change: https://github.com/NixOS/nixpkgs/commit/fdd01fd21c70e2674bead1c5333a5fe44ea1fd4d reproduces the issue.

**Comment by antifuchs** [comment]
And oops, trunk 0.20.1 (in nixpkgs release 24.05) doesn't allow `--release=true`. Ugh.

**Comment by ipetkov** [comment]
Hi @antifuchs thanks for the report, should be easy enough to conditionally set `=true` if the trunk version is >= `0.21`!

Will be fixed with https://github.com/ipetkov/crane/pull/736

**Comment by antifuchs** [comment]
Awesome, that works for me! Thank you (:
