### ISSUE TITLE
`buildDepsOnly` does not work without supplying `src` even with `dummySrc`

### ISSUE THREAD

**Issue by mdietrich16** [ipetkov/crane#748]
If supplying `dummySrc` and `src` to `buildDepsOnly`, it [throws a warning](https://github.com/ipetkov/crane/blob/f2b4b472983817021d9ffb60838b2b36b9376b20/lib/buildDepsOnly.nix#L38) stating that `src` will be ignored, which seems to be correct, except for the fact that only `src` [is used](https://github.com/ipetkov/crane/blob/f2b4b472983817021d9ffb60838b2b36b9376b20/lib/buildDepsOnly.nix#L16) to get the `Cargo.toml` file for project metadata and not `mkDummySrc`. Maybe `args.src` should be set to `dummySrc` [if it exists](https://github.com/ipetkov/crane/blob/f2b4b472983817021d9ffb60838b2b36b9376b20/lib/buildDepsOnly.nix#L34)?

**Comment by mdietrich16** [comment]
A workaround is not using `mkDummySrc` directly but supplying the arguments directly to `buildDepsOnly`, which might not work for special cases though.

**Comment by ipetkov** [comment]
Thanks for the report @mdietrich16 ! Should be fixed with https://github.com/ipetkov/crane/pull/750
