### ISSUE TITLE
Regression: `buildDepsOnly` crashes on having a `build.rs` in the config

### ISSUE THREAD

**Issue by vikanezrimaya** [ipetkov/crane#761]
**Describe the bug**
Presence of a build.rs without specifying crate name and version causes an eval failure due to rewritten Cargo.toml referring to a path in /nix/store, which is forbidden. This is a regression introduced in 9ed3180f45c2d1499e5af98c4ab7ffee8e886f5f (#750), found by bisection.

**Reproduction**
https://github.com/vikanezrimaya/crane-build.rs-bug-repro

**Comment by ipetkov** [comment]
Thanks for the report and reproduction @vikanezrimaya ! Should be fixed with https://github.com/ipetkov/crane/pull/762
