### ISSUE TITLE
Install phase picks up integration test binary

### ISSUE THREAD

**Issue by Trundle** [ipetkov/crane#765]
**Describe the bug**

With `doCheck = true` (the default), crane runs `cargo test`. When a binary crate has integration tests, this also builds the crate's binary under the same location as `cargo build` does, but with potentially different dependencies. For example, when a crate has `dev-dependencies` with different features, these are considered in `cargo test`, but not in `cargo build` (at least with resolver version 2). As the install phase runs after the check phase, it then picks up the binary built for the integration tests and copies it into the output.

`nixpkgs`'s `buildRustPackage` [copies the binary after the build phase to a temporary directory](https://github.com/NixOS/nixpkgs/blob/c1b72399a8d63accf5a2ee3b9b31ad663ace8b4d/pkgs/build-support/rust/hooks/cargo-install-hook.sh#L1C1-L15) (see [commit that introduced the copy](https://github.com/NixOS/nixpkgs/commit/d2694d936ef88d0d6028203105552efddf6db23d)).

**Reproduction**

See https://github.com/yaxitech/crane-test-binary-reproducer/

**Comment by ipetkov** [comment]
Hi @Trundle thanks for the report and the reproduction! It's really unfortunate cargo will clobber artifacts like this so I suppose a two step installation is the best we can do... Should be fixed with https://github.com/ipetkov/crane/pull/771
