### ISSUE TITLE
Heads-up: #[start] is being removed

### ISSUE THREAD

**Issue by RalfJung** [ipetkov/crane#767]
We are planning to remove the unstable `#[start]` attribute from the compiler, see https://github.com/rust-lang/rust/pull/134299 for rationale and further details. This repo showed up in a search for users of the attribute. For all we know, there's no good reason to use this attribute and you can do the following instead:
```rust
#![no_main]

#[no_mangle]
extern "C" fn main(argc: core::ffi::c_int, argv: *const *const u8) -> core::ffi::c_int {
  // ...
}
```

If that for some reason does not work, please let us know!

**Comment by ipetkov** [comment]
Thanks for the heads up! This was only used in some test code that I had copied from elsewhere and I have no problems taking it out :smile: 

Will be fixed with https://github.com/ipetkov/crane/pull/769
