### ISSUE TITLE
Add ability to customize compression level.

### ISSUE THREAD

**Issue by dpc** [ipetkov/crane#81]
As transfers times are often the bottleneck, would be nice if it was possible to pass custom arguments to `zstd` compression (like `-19` or even `-U -30`) and trade compute for storage space.

**Comment by ipetkov** [comment]
I'd be weary of adding too many customization options especially if we decide to not use `zstd` at some point.

FWIW it is possible [to disable the default behavior](https://github.com/ipetkov/crane/blob/5548a68f5d4d60a2315ab1232e6fba5528e71dc8/docs/API.md#installcargoartifactshook) by setting `doInstallCargoArtifacts = false;` and then using your own hook to do the compression.

It's not ergonomic, but I'd like to at least explore alternatives for optimizing the build artifacts #74 before we add more configurations here
