### ISSUE TITLE
Cargo is trying to fetch stuff out of band from `crates.io` after git&patched version was changed to release version. 

### ISSUE THREAD

**Issue by dpc** [ipetkov/crane#82]
https://github.com/fedimint/fedimint/runs/7830647635?check_suite_focus=true (corresponding [PR](https://github.com/fedimint/fedimint/pull/354) )

I might be misreading it, but it looks like `crane` lets `cargo` run with the previous state from cache, even thought the source of a dependency has changed. Cargo considers it missing, and tries to fetch it, but Nix does not appreciate such an impure conduct.

**Comment by ipetkov** [comment]
Sounds like the dependency vendoring has failed somehow (and why cargo is trying to fetch the deps directly).

Looks like the `PR` link above is incorrect, could you provide a link to the faulty commit? I wonder what changed so that vendoring doesn't work

**Comment by dpc** [comment]
I think this might have been an user error as well. My apologies.
