### ISSUE TITLE
Pass custom arguments to mkDerivation?

### ISSUE THREAD

**Issue by riceicetea** [ipetkov/crane#87]
Is there a way to do this? I've tried with the following flake.nix:

```nix
{
  description = "Your crate description here";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-22.05";

    crane = {
      url = "github:ipetkov/crane";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    flake-utils.url = "github:numtide/flake-utils";

    advisory-db = {
      url = "github:rustsec/advisory-db";
      flake = false;
    };

    flake-compat = {
      url = "github:edolstra/flake-compat";
      flake = false;
    };
  };

  outputs = { self, nixpkgs, crane, flake-utils, advisory-db, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs {
          inherit system;
        };

        inherit (pkgs) lib;

        craneLib = crane.lib.${system};
        src = ./.;
        desktop_item = pkgs.makeDesktopItem {
          name = "my_pkg";
          desktopName = "my_pkg";
          exec = "my_pkg %u";
          mimeTypes = [ ];
        };
        cargoArtifacts = craneLib.buildDepsOnly {
          inherit src;
        };

        package = craneLib.buildPackage {
          inherit cargoArtifacts src;
          preBuild = ''echo jhsdgfskhdjf sdkjf hjxhjvdxg yfhyhjdgfsdffgdskdgkjsdgjsdghsdf'';
          desktopItems = [ desktop_item ];
          nativeBuildInputs = [ pkgs.copyDesktopItems ];
        };
      in
      {
        checks =
          {
            inherit package;


            package-clippy = craneLib.cargoClippy {
              inherit cargoArtifacts src;
              cargoClippyExtraArgs = "--all-targets -- --deny warnings";
            };

            package-fmt = craneLib.cargoFmt {
              inherit src;
            };

            package-audit = craneLib.cargoAudit {
              inherit src advisory-db;
            };
          };

        packages.default = package;

        apps.default = flake-utils.lib.mkApp {
          drv = package;
        };

        devShells.default = pkgs.mkShell {
          inputsFrom = builtins.attrValues self.checks;

          nativeBuildInputs = with pkgs; [
            cargo
            rustc
          ];
        };
      });
}

```

one would imagine that this
- writes a my_package.desktop file into `result/share/applications`
- prints gibberish before building, 

yet none of this happens.

**Comment by riceicetea** [comment]
I figured it out. needs to be in buildDepsOnly or possibly both.

**Comment by ipetkov** [comment]
Glad you were able to figure it out @riceicetea !

For anyone else who may find this issue: anything extra passed into `buildPackage`/`cargoBuild`/`buildDepsOnly` is passed straight through to `stdenv.mkDerivation` (see the API docs for details on anything which _may not_ be passed through, but the list is small). Setting any of the [standard build phases](https://nixos.org/manual/nixpkgs/unstable/#sec-stdenv-phases) should get picked up and executed (e.g. setting `preBuildPhases = [ "myPrebuild" ]; myPreBuild = "echo foo";`)

Also worth noting that if `cargoArtifacts` is not specified to `buildPackage`/`cargoBuild`, then they will automatically call `buildDepsOnly` with the same arguments set that was passed in, but if the steps are explicitly separated as in the example above, then you may need to set the common parameters in both places should the build require it.

**Comment by dpc** [comment]
@ipetkov It might be worth putting this as a first section of https://github.com/ipetkov/crane/blob/master/docs/API.md
