### ISSUE TITLE
A command for `cargo doc`?

### ISSUE THREAD

**Issue by dpc** [ipetkov/crane#89]
`cargo doc` is as popular as `cargo clippy`, or maybe even more. Maybe it should get its own command.

**Comment by ipetkov** [comment]
Agree, this would be a good thing to add! The interesting part would be to cache any artifacts from the deps (not just docs but any rlibs or proc macros etc.) so they don't have to be rebuilt every time. Perhaps `buildDepsOnly` would already cache these for us but I don't remember off the top of my head

**Comment by dpc** [comment]
Oh. Interesting. I'll try to make more experients, but just want to point out that we (and probably lots of projects) will run `cargo doc  --no-deps` because they don't want documentation for dependencies.

This reminds me that we probably would like to run `cargo clippy --no-deps`, and maybe this can allow us to disable `cargo clippy` in `buildDepsOnly`. If so, some nicer way to control these (boolean flags instead of changing `buildPhaseCargoCommand`) might be nice to have.

This is all important because network throughput during fetching artifacts from `cachix` (or any other cache for that mater) is a bottleneck.

**Comment by ipetkov** [comment]
`cargo doc --no-deps` avoids building the docs for the crates (which is a good default flag to include) but cargo still needs to at least typecheck all crates. Imagine the documentation of your crate links to a type in another crate, rustdoc will need to know that the type exists, etc.

**Comment by dpc** [comment]
I just tried and indeed this won't work.

**Comment by dpc** [comment]
[Building `cargo doc` during `buildDepsOnly` works as expected.](https://github.com/fedimint/fedimint/pull/477/files)

**Comment by dpc** [comment]
BTW. Since we are talking about new commands, what about `cargo test`? Right now it's a `doCheck`, but it's very unintuitive. First - it is a separate `cargo` invocation. If you want to do `cargo test` as a separate step, you need to `doCheck = false`, and then you need have another `cargoBuild`, that depends on the dependencies only (since it doesn't reuse `cargo build` anyway, it seems) and `cargoBuildCommand = "true"` (to avoid re-doing the build of the project itself again).

**Comment by ipetkov** [comment]
> BTW. Since we are talking about new commands, what about cargo test?

Not a bad suggestion, I've opened #108 to track it, and #107 to add `cargoDoc`!
