### ISSUE TITLE
update docs on lock - no always lock must be in directory

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ipetkov/crane#92]
seems reasonable not have lock in repo if you have lock in released achieve

https://github.com/taiki-e/cargo-llvm-cov/pull/152#issuecomment-1107175353

**Comment by ipetkov** [comment]
Thanks for the report @dzmitry-lahoda ! There is a way to pass in your own `Cargo.lock` file by setting `cargoLock` on `buildDepsOnly`/`vendorCargoDeps`/`cargoBuild`/`buildPackage` but I'll highlight this in the FAQ section of the README
