### ISSUE TITLE
cargoAudit ignores audit.toml

### ISSUE THREAD

**Issue by DrRuhe** [ipetkov/crane#97]
I'd like to use cargo-audit, however without being able to specify an `audit.toml` I am not able to use crane to do the auditing.

I could not find a way to specify an `audit.toml`. Is this already possible?

**Comment by ipetkov** [comment]
Hey @DrRuhe thanks for the report!

I believe `audit.toml` should be optional. Could you share an example of the configuration you are using and the error(s) you are seeing?

**Comment by DrRuhe** [comment]
Sure, for an example:
I my small project [temp](https://gitlab.com/DrRuhe/temp) I use crane. However in the flake.nix I have the auditing disabled, since I use chrono in my project and cargo audit complains about this: 
```
Crate:     time
Version:   0.1.44
Title:     Potential segfault in the time crate
Date:      2020-11-18
ID:        RUSTSEC-2020-0071
URL:       https://rustsec.org/advisories/RUSTSEC-2020-0071
Solution:  Upgrade to >=0.2.23
Dependency tree:
time 0.1.44
└── chrono 0.4.22
    └── temp 0.1.0
```
Now, I think its good that I get reminded of it, but I have decided that RUSTSEC-2020-0071 is not relevant for this project, so I'd like to Ignore it, to not fail the check. And since this (and other calibrations) can be done in the audit.toml I'd like to be able to specify it.

**Comment by DrRuhe** [comment]
I now noticed the wording in the Issue might be misleading. I am able to use crane to do auditing, but without ways to adjust this, it does not add value, so I was forced to disable auditing alltogether.

**Comment by ipetkov** [comment]
Ah thanks for clarifying, I understand now! Looks like we're a bit overzealous when cleaning the source and only allowing the `Cargo.lock` to remain, when in reality we should be keeping the `audit.toml` as well

**Comment by DrRuhe** [comment]
I did some more testing. My understanding where the audit.toml should be placed was a bit off (I think in general cargo audit could handle this better but thats another thing).

__The `audit.toml` goes into the project local `.cargo` config directory.__ (I added this to the [temp](https://gitlab.com/DrRuhe/temp/-/blob/master/.cargo/audit.toml) project so you can see what I mean).

With this configuration, running `cargo audit` does not report RUSTSEC-2020-0071, so the config gets applied there.
However `nix flake check` still reports the error. From reading the changes in #98 I think you also thought the `audit.toml` was in the main project directory.

Therefore I think it is best to include (or rather no longer exclude) the whole `.cargo` directory since users can also make other cargo related settings.

**Comment by ipetkov** [comment]
Ah you're right I did make that mistake.

I think the filter is correct, it will keep _any_ `audit.toml` file in the project source, though the test needs to be updated

**Comment by ipetkov** [comment]
> However `nix flake check` still reports the error.

I took a look at the latest commit of your repo, it looks like `cargo-audit` is showing some unrelated warnings (for unmaintained crates) but seems like it is passing now (`RUSTSEC-2020-0071` doesn't trigger) so I believe the issue has been fixed. Going to resolve via #100 but feel free to reopen if it isn't!

**Comment by DrRuhe** [comment]
Oh man, I totally forgot to thank you! :)
